package se.smartgallery.app;

import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.graphics.*;import android.graphics.drawable.ColorDrawable;import android.net.Uri;import android.provider.MediaStore;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 final int BG=Color.rgb(12,16,22),CARD=Color.rgb(25,31,40),GREEN=Color.rgb(139,233,176); LinearLayout root; ArrayList<Item> all=new ArrayList<>(); int req=71;
 static class Item{long id,date,size;String name,bucket,mime;Uri uri;Item(long i,long d,long s,String n,String b,String m,Uri u){id=i;date=d;size=s;name=n;bucket=b;mime=m;uri=u;}}
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.READ_MEDIA_IMAGES)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.READ_MEDIA_IMAGES,Manifest.permission.READ_MEDIA_VIDEO},req);else load();}
 public void onRequestPermissionsResult(int r,String[]p,int[]g){super.onRequestPermissionsResult(r,p,g);load();}
 TextView tx(String s,int z,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.WHITE);v.setTypeface(null,bold?1:0);return v;}
 Button bt(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(Color.rgb(66,75,88)));return b;}
 void base(String title,String sub){ScrollView sv=new ScrollView(this);sv.setBackgroundColor(BG);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,38,18,50);root.setBackgroundColor(BG);root.addView(tx(title,28,true));TextView q=tx(sub,14,false);q.setTextColor(GREEN);q.setPadding(0,4,0,12);root.addView(q);sv.addView(root);setContentView(sv);}
 void load(){all.clear();query(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,"image/");query(MediaStore.Video.Media.EXTERNAL_CONTENT_URI,"video/");all.sort((a,b)->Long.compare(b.date,a.date));home();}
 void query(Uri u,String kind){String[]pr={MediaStore.MediaColumns._ID,MediaStore.MediaColumns.DISPLAY_NAME,MediaStore.MediaColumns.DATE_ADDED,MediaStore.MediaColumns.SIZE,MediaStore.MediaColumns.BUCKET_DISPLAY_NAME,MediaStore.MediaColumns.MIME_TYPE};try(Cursor c=getContentResolver().query(u,pr,null,null,null)){if(c==null)return;while(c.moveToNext()){long id=c.getLong(0),d=c.getLong(2)*1000,s=c.getLong(3);String n=c.getString(1),b=c.getString(4),m=c.getString(5);all.add(new Item(id,d,s,n,b==null?"Övrigt":b,m,Uri.withAppendedPath(u,""+id)));}}catch(Exception e){}}
 void home(){base("SMART GALLERY","Snabb sortering • privat • lokalt");long bytes=0;int vids=0;HashSet<String>b=new HashSet<>();for(Item i:all){bytes+=i.size;b.add(i.bucket);if(i.mime!=null&&i.mime.startsWith("video"))vids++;}note("📸 "+(all.size()-vids)+" foton   🎬 "+vids+" videor\n📁 "+b.size()+" album   💾 "+human(bytes));card("🕘 Alla foton","Tidslinje med de nyaste först",()->grid(all,"Alla foton"));card("📁 Album","Sortera efter Camera, Screenshots, Downloads och andra mappar",()->albums());card("🔎 Sök & filtrera","Sök filnamn, album, datum eller typ",()->search());card("🧹 Städa","Skärmbilder, stora filer och möjliga dubbletter",()->clean());card("⭐ Favoritval","Öppna Androids säkra fotoväljare",()->picker());card("🔒 Integritet","Smart Gallery analyserar biblioteket lokalt och laddar inte upp bilder.",()->privacy());}
 void note(String s){TextView v=tx(s,15,false);v.setTextColor(Color.LTGRAY);v.setPadding(6,8,6,8);root.addView(v);}
 interface Go{void go();}void card(String a,String b,Go g){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(16,14,16,14);c.setBackgroundColor(CARD);c.addView(tx(a,19,true));TextView d=tx(b,14,false);d.setTextColor(Color.LTGRAY);c.addView(d);c.setOnClickListener(v->g.go());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,7,0,0);root.addView(c,lp);}
 void back(){Button b=bt("← Tillbaka");b.setOnClickListener(v->home());root.addView(b,0);}
 void albums(){base("📁 ALBUM","Mappar på telefonen");back();TreeMap<String,Integer>m=new TreeMap<>(String.CASE_INSENSITIVE_ORDER);for(Item i:all)m.put(i.bucket,m.getOrDefault(i.bucket,0)+1);for(String k:m.keySet())card("📁 "+k,m.get(k)+" objekt",()->{ArrayList<Item>x=new ArrayList<>();for(Item i:all)if(i.bucket.equals(k))x.add(i);grid(x,k);});}
 void grid(ArrayList<Item> list,String title){base(title,list.size()+" objekt • tryck för helskärm");back();GridLayout g=new GridLayout(this);g.setColumnCount(3);for(int x=0;x<Math.min(list.size(),600);x++){Item i=list.get(x);ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.CENTER_CROP);im.setBackgroundColor(CARD);try{im.setImageBitmap(getContentResolver().loadThumbnail(i.uri,new android.util.Size(320,320),null));}catch(Exception e){}GridLayout.LayoutParams lp=new GridLayout.LayoutParams();lp.width=0;lp.height=330;lp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);lp.setMargins(2,2,2,2);im.setLayoutParams(lp);im.setOnClickListener(v->view(i));g.addView(im);}root.addView(g);}
 void view(Item i){base(i.name,i.bucket+" • "+human(i.size));back();ImageView im=new ImageView(this);im.setAdjustViewBounds(true);im.setScaleType(ImageView.ScaleType.FIT_CENTER);try{im.setImageURI(i.uri);}catch(Exception e){}root.addView(im,new LinearLayout.LayoutParams(-1,-2));note("📅 "+new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.getDefault()).format(new Date(i.date))+"\n"+(i.mime==null?"":i.mime));Button sh=bt("Dela");sh.setOnClickListener(v->{Intent x=new Intent(Intent.ACTION_SEND);x.setType(i.mime);x.putExtra(Intent.EXTRA_STREAM,i.uri);x.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(x,"Dela"));});root.addView(sh);}
 void search(){base("🔎 SÖK & FILTRERA","Filnamn • album • år/månad • foto/video");back();EditText e=new EditText(this);e.setHint("t.ex. screenshot, camera, 2026, video");e.setTextColor(Color.WHITE);e.setHintTextColor(Color.GRAY);root.addView(e);Button b=bt("Sök");b.setOnClickListener(v->{String q=e.getText().toString().toLowerCase(Locale.ROOT);ArrayList<Item>x=new ArrayList<>();SimpleDateFormat f=new SimpleDateFormat("yyyy-MM",Locale.ROOT);for(Item i:all){String z=(i.name+" "+i.bucket+" "+i.mime+" "+f.format(new Date(i.date))).toLowerCase(Locale.ROOT);if(z.contains(q))x.add(i);}grid(x,"Sök: "+q);});root.addView(b);}
 void clean(){base("🧹 STÄDA","Inget raderas automatiskt");back();ArrayList<Item>screens=new ArrayList<>(),large=new ArrayList<>(),dups=new ArrayList<>();HashMap<String,Item>seen=new HashMap<>();for(Item i:all){if(i.bucket.toLowerCase().contains("screen")||i.name.toLowerCase().contains("screenshot"))screens.add(i);if(i.size>25L*1024*1024)large.add(i);String k=i.name.replaceAll("\\(\\d+\\)","").toLowerCase()+":"+i.size;if(seen.containsKey(k))dups.add(i);else seen.put(k,i);}card("📱 Skärmbilder",screens.size()+" hittade",()->grid(screens,"Skärmbilder"));card("🐘 Stora filer",large.size()+" över 25 MB",()->grid(large,"Stora filer"));card("👯 Möjliga dubbletter",dups.size()+" med samma normaliserade namn och storlek",()->grid(dups,"Möjliga dubbletter"));note("Smart Gallery visar kandidater för granskning. Version 1.0 raderar aldrig automatiskt, vilket minskar risken att viktiga bilder försvinner.");}
 void picker(){Intent i=new Intent(MediaStore.ACTION_PICK_IMAGES);i.setType("image/*");startActivityForResult(i,90);}
 void privacy(){base("🔒 INTEGRITET","Lokalt först");back();note("Bilder och miniatyrer läses via Android MediaStore. Smart Gallery 1.0 har ingen internetbehörighet och skickar därför inte ditt fotobibliotek till någon server.\n\nNästa steg kan lägga till lokal bildklassificering, ansiktsgruppering och bättre likhetsanalys utan moln.");}
 String human(long n){if(n>1073741824)return String.format(Locale.ROOT,"%.1f GB",n/1073741824.0);if(n>1048576)return String.format(Locale.ROOT,"%.0f MB",n/1048576.0);return n/1024+" KB";}
 @Override public void onBackPressed(){home();}
}
