package se.smartoptimizer.toolbox;

import android.app.*;
import android.content.*;
import android.os.*;
import android.provider.Settings;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity101 extends MainActivity100 {
 @Override void show(){stopLive();base("S23 ULTRA TOOLBOX 10.1","Smart Dashboard • S23 Ultra • Android 16",false);smartDash101();card("⚡ Optimera nu","Säker kontroll som bara föreslår eller gör lämpliga åtgärder.",()->optimize101());card("🧠 Smart Advisor 8.0","Viktigt • Rekommenderat • Valfritt",()->advisor101());card("🚗 Jobb / GPS-läge 3.1","Förkontroll och snabbstart inför körning.",()->jobGps101());card("🛡️ Smart Debloat 8.1","Recovery Snapshot före ändringar och tydligare säkerhet.",()->debloat());card("🧯 Recovery Center 4.0","Snapshot, ändringshistorik och Android 16-återställning.",()->recovery101());card("🔋 Batterihistorik","Spara batteri, temperatur och laddstatus över tid.",()->batteryHistory101());card("🌡️ Thermal Guard","Bedömer värme för GPS, DeX, kamera och laddning.",()->thermalGuard101());card("🖥️ DeX-profil","Kontroll inför extern skärm och DeX-pass.",()->dexProfile101());card("🔄 Efter Samsung Update 2.0","Snapshot och kontroller efter One UI-uppdatering.",()->update101());card("📱 S23 Ultra Guide","Skärm, batteri, GPS, DeX, kamera och S Pen.",()->guide101());sec("Alla verktyg");card("📡 Live Performance Monitor","Temperatur, RAM, batteri och laddning.",()->liveMonitor());card("💾 Storage Analyzer","Lagringsanalys och genvägar.",()->storageAnalyzer());card("⚙️ Performance Profiles 2.0","Profiler för olika användning.",()->profiles90());card("📦 App Manager 2.1","Installerade appar och detaljer.",()->apps89());card("🔧 Toolbox Self-Test 2.0","Kontroll efter Android/Samsung-uppdatering.",()->selfTest100());card("📸 Camera Guide 6.0","Praktiska kamerainställningar.",()->camera100());card("🔧 Shizuku Tools",shStatus(),()->shPage());card("🕘 Historik","Senaste Toolbox-åtgärder.",()->history());}
 void smartDash101(){int issues=issueCount100();String health=issues==0?"🟢 BRA":issues<=2?"🟡 KONTROLLERA":"🔴 ÅTGÄRDA";note("TELEFONENS HÄLSA  "+health+"\n🔋 "+level()+"%   🌡️ "+fmt(temp())+"°C   🧠 "+ram()+"% RAM\n💾 "+free()+" GB ledigt   🔧 "+(shOk()?"Shizuku OK":"Shizuku av")+"\nProfil: "+p.getString("profile","Standard"));}
 void optimize101(){base("⚡ OPTIMERA NU","Säker kontroll • inga aggressiva ändringar",true);int n=0;if(temp()>=warnTemp()){note("🌡️ Temperaturen är hög. Rekommendation: minska belastning innan optimering.");n++;}if(free()<10){note("💾 Lagringen börjar bli låg.");btn("Öppna Storage Analyzer",()->storageAnalyzer());n++;}if(!shOk()){note("🔧 Shizuku är inte redo. Vanliga Toolbox-funktioner fungerar ändå.");n++;}if(disabledKnown100()>0){note("🛡️ Avaktiverade Toolbox-appar hittades. De ändras inte automatiskt.");btn("Öppna Recovery Center",()->recovery101());n++;}saveBatterySample101();if(n==0)note("✅ Telefonen ser bra ut. Inga onödiga ändringar gjordes.");btn("Kör Health Check",()->healthCheck());}
 void advisor101(){base("🧠 SMART ADVISOR 8.0","Prioriterade rekommendationer",true);boolean any=false;if(!signatureOk()){sec("🔴 VIKTIGT");note("Toolbox-signeringen behöver kontrolleras.");any=true;}if(temp()>=hotTemp()){sec("🔴 VIKTIGT");note("Temperaturen är "+fmt(temp())+"°C. Pausa tung belastning eller laddning.");any=true;}if(!shOk()||free()<10||ram()>=95){sec("🟡 REKOMMENDERAT");if(!shOk())note("Starta Shizuku för avancerade funktioner.");if(free()<10)note("Frigör lagring; "+free()+" GB återstår.");if(ram()>=95)note("RAM-användningen är "+ram()+"%.");any=true;}if(disabledKnown100()>0){sec("🔵 VALFRITT");note("Recovery Center kan granska "+disabledKnown100()+" avaktiverade Toolbox-paket.");any=true;}if(!any)note("🟢 Inga viktiga rekommendationer just nu.");btn("Optimera nu",()->optimize101());}
 void jobGps101(){base("🚗 JOBB / GPS-LÄGE 3.1","Inför navigation",true);boolean ok=temp()<hotTemp()&&(level()>=25||status()==BatteryManager.BATTERY_STATUS_CHARGING)&&free()>=5;note((ok?"🟢 REDO FÖR GPS-PASS":"🟡 KONTROLLERA FÖRE START")+"\n🔋 "+level()+"% • 🌡️ "+fmt(temp())+"°C • 💾 "+free()+" GB");btn("Performance Profiles",()->profiles90());btn("Starta Google Maps",()->launchPkg100("com.google.android.apps.maps","Google Maps"));btn("Platsinställningar",()->open(Settings.ACTION_LOCATION_SOURCE_SETTINGS));btn("Thermal Guard",()->thermalGuard101());}
 @Override void debloat(){saveRecoverySnapshot100();super.debloat();}
 void recovery101(){base("🧯 RECOVERY CENTER 4.0","Snapshot • historik • säker återställning",true);String s=p.getString("recovery_snapshot100","");note(s.isEmpty()?"Ingen Recovery Snapshot sparad.":"Snapshot: "+p.getString("recovery_snapshot_time100","okänd")+"\n"+snapshotSummary100(s));note("Android 16 kan neka shell-återställning för vissa systemappar. Då använder Toolbox appinställningarna i stället för osäkra kringvägar.");btn("Spara ny Snapshot",()->saveRecoverySnapshot100());btn("Recovery Assistant",()->recoveryAssistant95());btn("Historik",()->history());}
 void saveBatterySample101(){String old=p.getString("battery_history101","");String t=new SimpleDateFormat("MM-dd HH:mm",Locale.getDefault()).format(new Date());String row=t+" • "+level()+"% • "+fmt(temp())+"°C • "+charge();String all=row+(old.isEmpty()?"":"\n"+old);String[]ls=all.split("\n");StringBuilder b=new StringBuilder();for(int i=0;i<Math.min(ls.length,20);i++){if(i>0)b.append('\n');b.append(ls[i]);}p.edit().putString("battery_history101",b.toString()).apply();}
 void batteryHistory101(){saveBatterySample101();base("🔋 BATTERIHISTORIK","Senaste 20 mätningarna",true);note(p.getString("battery_history101","Ingen historik ännu."));btn("Charging Test Pro",()->battery89());btn("Battery Health",()->batteryHealth());}
 void thermalGuard101(){base("🌡️ THERMAL GUARD","GPS • DeX • kamera • laddning",true);float t=temp();String state=t>=hotTemp()?"🔴 HÖG":t>=warnTemp()?"🟡 VARM":"🟢 NORMAL";note("Temperatur: "+fmt(t)+"°C • "+state+"\n"+(t>=hotTemp()?"Undvik tung GPS/DeX/kamera samtidigt med snabbladdning tills temperaturen sjunkit.":t>=warnTemp()?"Håll koll vid längre GPS-, DeX- eller kamerapass.":"Temperaturen är lämplig för normal användning."));btn("Live Monitor",()->liveMonitor());btn("Temperaturgränser",()->thermalAlerts());}
 void dexProfile101(){base("🖥️ DEX-PROFIL","Kontroll inför DeX",true);note("Skärmar: "+externalDisplays()+" • RAM "+ram()+"% • 🌡️ "+fmt(temp())+"°C • 🔋 "+level()+"%\n"+(temp()<hotTemp()?"🟢 Temperatur OK":"🔴 Låt telefonen svalna före tung DeX-användning"));btn("Performance Profiles",()->profiles90());btn("Display-inställningar",()->open(Settings.ACTION_DISPLAY_SETTINGS));btn("Live Monitor",()->liveMonitor());}
 void update101(){base("🔄 EFTER SAMSUNG UPDATE 2.0","Kontroll efter One UI / Android-uppdatering",true);note("Kör kontrollen efter en systemuppdatering. Toolbox granskar Shizuku, appar, lagring och grundfunktioner utan att återställa systeminställningar automatiskt.");btn("Kör Self-Test",()->selfTest100());btn("App Change Watch",()->appChangeWatch());btn("Spara nytt Recovery Snapshot",()->saveRecoverySnapshot100());btn("Recovery Assistant",()->recoveryAssistant95());}
 void guide101(){base("📱 S23 ULTRA GUIDE","Snabbguide för telefonens viktigaste styrkor",true);sec("Skärm");note("Använd adaptiv uppdateringsfrekvens för mjuk känsla och låt ljusstyrkan anpassas automatiskt till miljön.");sec("Batteri");note("Undvik onödig värme. Thermal Guard och laddhistoriken är mer användbara än aggressiv processrensning.");sec("GPS / jobb");note("Kontrollera plats, batteri och temperatur före långa navigationspass.");sec("DeX");note("Håll koll på temperatur och RAM vid långa pass med extern skärm.");sec("Kamera");note("12 MP är bra standard; 3x för porträtt, 200 MP främst i bra ljus.");sec("S Pen");note("Använd S Pen för precisa markeringar, anteckningar och fjärrfunktioner som stöds av dina Samsung-appar.");btn("Camera Guide 6.0",()->camera100());}
}
