package se.smartoptimizer.toolbox;

import android.app.*;
import android.os.*;
import android.content.*;
import android.content.pm.*;
import android.graphics.Color;
import android.net.Uri;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.lang.reflect.Method;
import java.text.SimpleDateFormat;
import java.util.*;
import rikka.shizuku.Shizuku;

public class MainActivity extends Activity {
  LinearLayout root; SharedPreferences p; Handler h=new Handler(Looper.getMainLooper()); Runnable watch; boolean home=true;
  final int SH=8801, EXP=8802; final int BG=Color.rgb(12,16,22), CARD=Color.rgb(24,30,40), GREEN=Color.rgb(105,255,145), AMBER=Color.rgb(255,196,80);
  interface Go{void run();}
  String[][] PK={
    {"Samsung Free","com.samsung.android.app.spage","Säker","Samsung","Nyhets-/innehållspanel."},
    {"Global Goals","com.samsung.sree","Säker","Samsung","Samsung Global Goals."},
    {"AR Zone","com.samsung.android.arzone","Säker","Samsung","AR-effekter och emoji."},
    {"Samsung Kids","com.samsung.android.kidsinstaller","Säker","Samsung","Samsung Kids-installerare."},
    {"Samsung Members","com.samsung.android.voc","Valfritt","Samsung","Support och diagnostik."},
    {"Bixby Voice","com.samsung.android.bixby.agent","Försiktig","Samsung","Bixby-röstfunktioner kan påverkas."},
    {"SmartThings","com.samsung.android.oneconnect","Försiktig","Samsung","Påverkar SmartThings och anslutna enheter."},
    {"Samsung Health","com.sec.android.app.shealth","Försiktig","Samsung","Påverkar Samsung Health och vissa Watch-funktioner."},
    {"Samsung Cloud","com.samsung.android.scloud","Försiktig","Samsung","Kan påverka synk och backup."},
    {"Google TV","com.google.android.videos","Säker","Google","Google TV."},
    {"Google Meet","com.google.android.apps.tachyon","Valfritt","Google","Google Meet."},
    {"YouTube Music","com.google.android.apps.youtube.music","Valfritt","Google","YouTube Music."},
    {"Google One","com.google.android.apps.subscriptions.red","Valfritt","Google","Google One och backup."},
    {"Android Auto","com.google.android.projection.gearhead","Försiktig","Google","Behåll om du använder Android Auto."},
    {"LinkedIn","com.linkedin.android","Säker","Övrigt","LinkedIn."},
    {"Meta App Manager","com.facebook.appmanager","Valfritt","Meta","Meta bakgrundskomponent."},
    {"Meta Services","com.facebook.services","Valfritt","Meta","Meta tjänster."},
    {"Meta Installer","com.facebook.system","Valfritt","Meta","Meta installerare."}
  };
  final Shizuku.OnRequestPermissionResultListener sl=(q,g)->{if(q==SH){toast(g==PackageManager.PERMISSION_GRANTED?"Shizuku behörig":"Behörighet nekad");show();}};

  public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("toolbox",0);try{Shizuku.addRequestPermissionResultListener(sl);}catch(Throwable e){}systemCheck();sampleBaseline();show();}
  public void onBackPressed(){if(!home)show();else super.onBackPressed();}
  protected void onDestroy(){stop();try{Shizuku.removeRequestPermissionResultListener(sl);}catch(Throwable e){}super.onDestroy();}

  TextView text(String s,int z,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.WHITE);v.setTypeface(null,bold?1:0);return v;}
  void note(String s){TextView v=text(s,15,false);v.setTextColor(Color.LTGRAY);v.setPadding(8,7,8,7);root.addView(v);}
  void sec(String s){TextView v=text(s,20,true);v.setTextColor(GREEN);v.setPadding(0,18,0,6);root.addView(v);}
  Button btn(String s,Go g){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(Color.rgb(80,86,96)));b.setOnClickListener(v->g.run());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,4,0,4);root.addView(b,lp);return b;}
  void card(String a,String b,Go g){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(16,13,16,13);c.setBackgroundColor(CARD);c.addView(text(a,19,true));TextView d=text(b,14,false);d.setTextColor(Color.LTGRAY);c.addView(d);c.setOnClickListener(v->g.run());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,7,0,0);root.addView(c,lp);}
  void base(String a,String b,boolean back){stop();home=!back;ScrollView s=new ScrollView(this);s.setBackgroundColor(BG);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,26+bar(),18,50);root.setBackgroundColor(BG);getWindow().setStatusBarColor(BG);if(back)btn("← Tillbaka",()->show());root.addView(text(a,27,true));TextView q=text(b,15,false);q.setTextColor(GREEN);q.setPadding(0,4,0,10);root.addView(q);s.addView(root);setContentView(s);}
  int bar(){int i=getResources().getIdentifier("status_bar_height","dimen","android");return i>0?getResources().getDimensionPixelSize(i):0;}

  void show(){base("S23 ULTRA TOOLBOX 8.8","Dashboard 4.0 • Smart Advisor 4.0 • Recovery 2.0",false);dashboard();if(p.getBoolean("update",false))card("🆕 Efter Samsung-uppdatering","Kontrollera om paket eller inställningar ändrats.",()->afterUpdate());card("🧠 Smart Advisor 4.0","Jämför nuläget med din lokala historik.",()->advisor());card("🛡️ Smart Debloat 7.0","Risk, leverantör, beroendevarning och failsafe.",()->debloat());card("📦 App Manager 2.0","Sök, filtrera och inspektera installerade appar.",()->apps());card("🌡️ Thermal Watch 4.0","Trend, min/max/medel och sparad historik.",()->thermal());card("⚡ Charging Test Pro","1/5/10 min • effekt • temperatur • min/medel/max.",()->battery());card("🚗 GPS/Jobbläge","Skärm vaken, rotation och återställning.",()->profiles());card("🖥️ DeX Center 2.0","Extern skärm, temperatur och snabbval.",()->dex());card("🧯 Recovery Center 2.0","Ångra senaste och se exakt vad Toolbox ändrat.",()->recovery());card("💾 Backup / Diagnostik","Exportera rapport och Toolbox-status.",()->diag());card("🔧 Shizuku Tools",shStatus(),()->shPage());card("📸 Camera Guide 5.1","S23 Ultra-råd för foto och video.",()->camera());card("🕘 Historik","Vad har Toolbox ändrat?",()->history());}

  void dashboard(){LinearLayout a=new LinearLayout(this);a.setOrientation(LinearLayout.HORIZONTAL);a.addView(chip("🌡️ "+fmt(temp())+"°C\n"+tname()));a.addView(chip("🔋 "+level()+"%\n"+charge()));root.addView(a);LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.HORIZONTAL);b.addView(chip("🧠 RAM "+ram()+"%\n"+(ram()>90?"Hög":"Normal")));b.addView(chip("🔧 Shizuku\n"+(shOk()?"Behörig":"Ej redo")));root.addView(b);note("Health "+score()+"/100 • Profil: "+p.getString("profile","Standard")+" • 💾 "+free()+" GB • 🛡️ "+safe()+" säkra förslag");}
  TextView chip(String s){TextView v=text(s,14,true);v.setPadding(10,9,10,9);v.setBackgroundColor(CARD);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.setMargins(3,3,3,3);v.setLayoutParams(lp);return v;}

  Intent bi(){return registerReceiver(null,new IntentFilter(Intent.ACTION_BATTERY_CHANGED));}
  int level(){Intent i=bi();return i==null?-1:i.getIntExtra(BatteryManager.EXTRA_LEVEL,-1);} float temp(){Intent i=bi();return i==null?0:i.getIntExtra(BatteryManager.EXTRA_TEMPERATURE,0)/10f;} int volt(){Intent i=bi();return i==null?0:i.getIntExtra(BatteryManager.EXTRA_VOLTAGE,0);} int status(){Intent i=bi();return i==null?0:i.getIntExtra(BatteryManager.EXTRA_STATUS,0);} long ua(){try{return((BatteryManager)getSystemService(BATTERY_SERVICE)).getLongProperty(BatteryManager.BATTERY_PROPERTY_CURRENT_NOW);}catch(Exception e){return 0;}}
  String charge(){return status()==BatteryManager.BATTERY_STATUS_CHARGING?"Laddar":status()==BatteryManager.BATTERY_STATUS_FULL?"Full":"Batteri";} String fmt(float x){return String.format(Locale.ROOT,"%.1f",x);} String tname(){float x=temp();return x>=43?"Mycket varm":x>=40?"Varm":x>=35?"Normal/varm":"Normal";}
  int ram(){ActivityManager a=(ActivityManager)getSystemService(ACTIVITY_SERVICE);ActivityManager.MemoryInfo m=new ActivityManager.MemoryInfo();a.getMemoryInfo(m);return(int)((m.totalMem-m.availMem)*100/m.totalMem);} long free(){return new StatFs(getFilesDir().getPath()).getAvailableBytes()/1073741824L;}
  int score(){int s=100;if(temp()>=43)s-=22;else if(temp()>=40)s-=12;if(ram()>92)s-=8;if(free()<20)s-=8;if(!shOk())s-=4;if(level()<15)s-=5;return Math.max(0,s);} int safe(){int n=0;for(String[]a:PK)if(a[2].equals("Säker")&&installed(a[1])&&enabled(a[1]))n++;return n;}

  void sampleBaseline(){long now=System.currentTimeMillis(),last=p.getLong("baseline_time",0);if(now-last<30*60*1000)return;float oldT=p.getFloat("base_temp",temp()),oldR=p.getFloat("base_ram",ram());p.edit().putFloat("base_temp",oldT*.85f+temp()*.15f).putFloat("base_ram",oldR*.85f+ram()*.15f).putLong("baseline_time",now).apply();}
  void advisor(){base("🧠 SMART ADVISOR 4.0","Jämför nuläget med telefonens lokala baslinje",true);float bt=p.getFloat("base_temp",temp()),br=p.getFloat("base_ram",ram());note("Nu: "+fmt(temp())+"°C • RAM "+ram()+"% • "+free()+" GB ledigt\nBaslinje: "+fmt(bt)+"°C • RAM "+fmt(br)+"%");sec("Rekommendationer");int n=0;if(temp()>bt+4||temp()>=40)note(++n+". 🔥 Varmare än normalt. Vänta med benchmark/gaming.");if(ram()>br+18)note(++n+". 🧠 RAM ligger tydligt över din normala nivå. Android får först hantera minnet själv.");if(free()<20)note(++n+". 💾 Frigör lagring före större uppdateringar.");if(!shOk())note(++n+". 🔧 Starta Shizuku för Debloat-funktionerna.");if(safe()>0)note(++n+". 🛡️ "+safe()+" säkra paket kan granskas i Debloat.");if(n==0)note("✅ Inga viktiga åtgärder just nu.");btn("Öppna Debloat 7.0",()->debloat());log("Advisor 4.0: Health "+score());}

  void debloat(){base("🛡️ SMART DEBLOAT 7.0","Samsung • Google • Meta • risk • Recovery",true);note(shStatus());btn("✨ Rekommenderad säker batch",()->recommended());String last="";for(String[]a:PK)if(installed(a[1])){if(!a[3].equals(last)){sec(a[3]);last=a[3];}TextView z=text(a[0]+" • "+a[2],18,true);z.setTextColor(a[2].equals("Försiktig")?AMBER:GREEN);root.addView(z);note(a[4]+"\n"+a[1]+"\nStatus: "+(enabled(a[1])?"✅ Aktiv":"⛔ Avaktiverad"));if(enabled(a[1]))btn("Avaktivera "+a[0],()->ask(a));else btn("Återställ "+a[0],()->shell("pm enable --user 0 "+a[1],a[1],false));}sec("Skydd");note("Systemkritiska paket finns inte i rekommenderad batch. Varje ändring loggas och kan återställas.");}
  void recommended(){ArrayList<String[]> l=new ArrayList<>();for(String[]a:PK)if(a[2].equals("Säker")&&installed(a[1])&&enabled(a[1]))l.add(a);if(l.isEmpty()){toast("Inga säkra aktiva förslag");return;}StringBuilder s=new StringBuilder("Snapshot skapas först.\n\n");for(String[]a:l)s.append("• ").append(a[0]).append("\n");new AlertDialog.Builder(this).setTitle("Granska batch").setMessage(s).setNegativeButton("Avbryt",null).setPositiveButton("Avaktivera "+l.size(),(d,w)->{snapshot();for(String[]a:l)shell("pm disable-user --user 0 "+a[1],a[1],true);}).show();}
  void ask(String[]a){String warn=a[2].equals("Försiktig")?"\n\n⚠️ Den här appen kan påverka en funktion du använder.":"";new AlertDialog.Builder(this).setTitle("Avaktivera "+a[0]+"?").setMessage(a[4]+"\nRisk: "+a[2]+warn+"\n\nRecovery Center kan återställa.").setNegativeButton("Avbryt",null).setPositiveButton("Avaktivera",(d,w)->{snapshot();shell("pm disable-user --user 0 "+a[1],a[1],true);}).show();}

  void apps(){base("📦 APP MANAGER 2.0","Sök • system • användare • Samsung • Google • avaktiverade",true);EditText e=new EditText(this);e.setHint("Sök app eller paket…");e.setTextColor(Color.WHITE);e.setHintTextColor(Color.GRAY);root.addView(e);btn("Alla",()->appList(e.getText().toString(),0));btn("Systemappar",()->appList(e.getText().toString(),1));btn("Användarappar",()->appList(e.getText().toString(),2));btn("Avaktiverade",()->appList(e.getText().toString(),3));btn("Samsung",()->appList(e.getText().toString(),4));btn("Google",()->appList(e.getText().toString(),5));}
  void appList(String q,int f){PackageManager pm=getPackageManager();ArrayList<ApplicationInfo>m=new ArrayList<>();String z=q.toLowerCase(Locale.ROOT);for(ApplicationInfo a:pm.getInstalledApplications(0)){boolean sy=(a.flags&ApplicationInfo.FLAG_SYSTEM)!=0;String n=""+pm.getApplicationLabel(a);if(f==1&&!sy||f==2&&sy||f==3&&a.enabled)continue;if(f==4&&!a.packageName.startsWith("com.samsung")&&!a.packageName.startsWith("com.sec"))continue;if(f==5&&!a.packageName.startsWith("com.google"))continue;if(z.isEmpty()||n.toLowerCase().contains(z)||a.packageName.toLowerCase().contains(z))m.add(a);}m.sort((a,b)->(""+pm.getApplicationLabel(a)).compareToIgnoreCase(""+pm.getApplicationLabel(b)));int n=Math.min(250,m.size());String[]x=new String[n];for(int i=0;i<n;i++)x[i]=pm.getApplicationLabel(m.get(i))+"\n"+m.get(i).packageName+(m.get(i).enabled?" • Aktiv":" • Avaktiverad");new AlertDialog.Builder(this).setTitle("Matchningar: "+m.size()).setItems(x,(d,i)->inspect(m.get(i).packageName)).setNegativeButton("Stäng",null).show();}
  void inspect(String x){try{PackageManager pm=getPackageManager();ApplicationInfo a=pm.getApplicationInfo(x,0);PackageInfo pi=pm.getPackageInfo(x,0);boolean sy=(a.flags&ApplicationInfo.FLAG_SYSTEM)!=0;new AlertDialog.Builder(this).setTitle(""+pm.getApplicationLabel(a)).setMessage("Paket: "+x+"\nVersion: "+pi.versionName+"\nTyp: "+(sy?"Systemapp":"Användarapp")+"\nStatus: "+(a.enabled?"Aktiv":"Avaktiverad")+"\nSenast uppdaterad: "+new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()).format(new Date(pi.lastUpdateTime))).setNeutralButton("Appinfo",(d,w)->startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+x)))).setNegativeButton("Kopiera ID",(d,w)->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("pkg",x));toast("Kopierat");}).setPositiveButton("OK",null).show();}catch(Exception e){toast("Paketet hittades inte");}}

  void thermal(){base("🌡️ THERMAL WATCH 4.0","Trend • min • max • medel • historik",true);float[]s=stats("temps");note("Aktuellt: "+fmt(temp())+"°C • "+tname());if(s[3]>0)note("Min "+fmt(s[0])+"°C • Max "+fmt(s[1])+"°C • Medel "+fmt(s[2])+"°C • "+(int)s[3]+" mätningar\nTrend: "+trend());btn("Starta 1 minut",()->startTemp(12));btn("Starta 5 minuter",()->startTemp(60));btn("Starta 15 minuter",()->startTemp(180));btn("Starta 30 minuter",()->startTemp(360));sec("Senaste 20");note(latest("temps",20));btn("Rensa temperaturhistorik",()->{p.edit().remove("temps").apply();thermal();});}
  void startTemp(int n){stop();final int[]c={0};watch=new Runnable(){public void run(){save("temps",temp(),720);if(++c[0]<n)h.postDelayed(this,5000);else{watch=null;toast("Thermal Watch klar");thermal();}}};h.post(watch);}
  void stop(){if(watch!=null){h.removeCallbacks(watch);watch=null;}}
  void save(String k,float v,int max){String now=new SimpleDateFormat("MM-dd HH:mm:ss",Locale.getDefault()).format(new Date()),old=p.getString(k,""),all=now+" • "+v+(old.isEmpty()?"":"\n"+old);String[]a=all.split("\n");StringBuilder b=new StringBuilder();for(int i=0;i<Math.min(max,a.length);i++){if(i>0)b.append("\n");b.append(a[i]);}p.edit().putString(k,b.toString()).apply();}
  float[]stats(String k){float mi=999,ma=-999,sum=0;int n=0;for(String l:p.getString(k,"").split("\n"))try{float x=Float.parseFloat(l.substring(l.lastIndexOf("•")+1).trim());mi=Math.min(mi,x);ma=Math.max(ma,x);sum+=x;n++;}catch(Exception e){}return n==0?new float[]{0,0,0,0}:new float[]{mi,ma,sum/n,n};}
  String latest(String k,int n){String[]a=p.getString(k,"Ingen historik").split("\n");StringBuilder b=new StringBuilder();for(int i=0;i<Math.min(n,a.length);i++)b.append(a[i]).append("\n");return b.toString().trim();}
  String trend(){String[]a=p.getString("temps","").split("\n");if(a.length<4)return"För lite data";try{float x=Float.parseFloat(a[0].substring(a[0].lastIndexOf("•")+1).trim()),y=Float.parseFloat(a[Math.min(a.length-1,11)].substring(a[Math.min(a.length-1,11)].lastIndexOf("•")+1).trim()),d=x-y;return d>.7?"Stigande +"+fmt(d)+"°C":d<-.7?"Sjunkande "+fmt(d)+"°C":"Stabil";}catch(Exception e){return"Okänd";}}

  void battery(){base("⚡ CHARGING TEST PRO","Sensorbaserad ström/effekt • temperatur • sparade serier",true);long u=ua();double v=volt()/1000.0,w=v*Math.abs(u)/1000000.0;String cur=Math.abs(u)<1000?"Ingen mätbar ström just nu":String.format(Locale.ROOT,"%.0f mA",u/1000.0);note("Batteri: "+level()+"%\nTemperatur: "+fmt(temp())+"°C\nSpänning: "+String.format(Locale.ROOT,"%.3f",v)+" V\nStröm: "+cur+"\nUppskattad effekt: "+String.format(Locale.ROOT,"%.2f",w)+" W\nStatus: "+charge());float[]s=stats("watts");if(s[3]>0)note("Senaste serie • Min "+fmt(s[0])+" W • Max "+fmt(s[1])+" W • Medel "+fmt(s[2])+" W");note("Effekten är en Android-sensoruppskattning, inte laddarens märkta watt.");btn("Starta 1 min",()->startPower(12));btn("Starta 5 min",()->startPower(60));btn("Starta 10 min",()->startPower(120));btn("Rensa laddningsserie",()->{p.edit().remove("watts").apply();battery();});}
  void startPower(int n){stop();p.edit().remove("watts").apply();final int[]c={0};watch=new Runnable(){public void run(){float w=(float)(volt()/1000.0*Math.abs(ua())/1000000.0);save("watts",w,240);save("chargeTemps",temp(),240);if(++c[0]<n)h.postDelayed(this,5000);else{watch=null;float[]s=stats("watts"),t=stats("chargeTemps");String out="Effekt "+fmt(s[0])+" / "+fmt(s[2])+" / "+fmt(s[1])+" W • Temp max "+fmt(t[1])+"°C";p.edit().putString("last_charge_test",out).apply();log("Laddningsprov: "+out);toast("Laddningsprov klart");battery();}}};h.post(watch);}

  void profiles(){base("🚗 GPS / JOBBLÄGE","Profiler som kan återställas",true);note("Aktiv profil: "+p.getString("profile","Standard"));btn("Balanserad",()->profile("Balanserad",60000,true,true,false));btn("Batteri",()->profile("Batteri",30000,true,false,false));btn("Gaming",()->profile("Gaming",120000,false,true,false));btn("Bil/GPS",()->profile("Bil/GPS",600000,true,true,true));btn("DeX",()->profile("DeX",600000,true,true,false));btn("Återställ tidigare läge",()->restoreProfile());}
  void remember(){if(p.contains("pre_timeout"))return;try{p.edit().putInt("pre_timeout",Settings.System.getInt(getContentResolver(),Settings.System.SCREEN_OFF_TIMEOUT,60000)).putInt("pre_bright",Settings.System.getInt(getContentResolver(),Settings.System.SCREEN_BRIGHTNESS_MODE,1)).putInt("pre_rotate",Settings.System.getInt(getContentResolver(),Settings.System.ACCELEROMETER_ROTATION,1)).apply();}catch(Exception e){}}
  void profile(String n,int t,boolean a,boolean o,boolean keep){if(!writeOk())return;remember();try{Settings.System.putInt(getContentResolver(),Settings.System.SCREEN_OFF_TIMEOUT,t);Settings.System.putInt(getContentResolver(),Settings.System.SCREEN_BRIGHTNESS_MODE,a?1:0);Settings.System.putInt(getContentResolver(),Settings.System.ACCELEROMETER_ROTATION,o?1:0);if(keep)getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);else getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);p.edit().putString("profile",n).apply();log("Profil aktiverad: "+n);toast(n+" aktiverad");}catch(Exception e){toast("Kunde inte ändra allt");}}
  void restoreProfile(){if(!writeOk())return;if(!p.contains("pre_timeout")){toast("Ingen sparad profilbas");return;}try{Settings.System.putInt(getContentResolver(),Settings.System.SCREEN_OFF_TIMEOUT,p.getInt("pre_timeout",60000));Settings.System.putInt(getContentResolver(),Settings.System.SCREEN_BRIGHTNESS_MODE,p.getInt("pre_bright",1));Settings.System.putInt(getContentResolver(),Settings.System.ACCELEROMETER_ROTATION,p.getInt("pre_rotate",1));p.edit().remove("pre_timeout").remove("pre_bright").remove("pre_rotate").putString("profile","Standard").apply();getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);log("Profil återställd");toast("Återställt");}catch(Exception e){toast("Misslyckades");}}

  void dex(){base("🖥️ DEX CENTER 2.0","Extern skärm • temperatur • laddning • snabbval",true);android.hardware.display.DisplayManager d=(android.hardware.display.DisplayManager)getSystemService(DISPLAY_SERVICE);int n=d==null?1:d.getDisplays().length;note((n>1?"✅ Extern skärm upptäckt":"Ingen extern skärm upptäckt")+"\nTemperatur "+fmt(temp())+"°C • Batteri "+level()+"% • "+charge()+" • RAM "+ram()+"%");btn("Aktivera DeX-profil",()->profile("DeX",600000,true,true,false));btn("Återställ profil",()->restoreProfile());btn("Skärminställningar",()->open(Settings.ACTION_DISPLAY_SETTINGS));btn("Ljudinställningar",()->open(Settings.ACTION_SOUND_SETTINGS));}

  void recovery(){base("🧯 RECOVERY CENTER 2.0","Ångra • snapshot • spårade ändringar",true);note("Toolbox-spårade paket: "+p.getStringSet("disabled",new HashSet<>()).size()+"\nSenaste ändring: "+p.getString("last_change","Ingen"));btn("Ångra senaste paketändringen",()->undo());btn("Återställ senaste snapshot",()->restoreSnap());btn("Återställ allt Toolbox avaktiverat",()->restoreAll());btn("Återställ profilinställningar",()->restoreProfile());sec("Vad har Toolbox ändrat?");note(p.getString("history","Ingen aktivitet ännu."));}
  void snapshot(){Set<String>s=new HashSet<>();for(String[]a:PK)if(installed(a[1])&&enabled(a[1]))s.add(a[1]);p.edit().putStringSet("snapshot",s).putLong("snapshot_time",System.currentTimeMillis()).apply();log("Snapshot skapad");}
  void undo(){String x=p.getString("last_pkg","");if(x.isEmpty()){toast("Ingen ändring att ångra");return;}boolean d=p.getBoolean("last_disabled",false);shell((d?"pm enable --user 0 ":"pm disable-user --user 0 ")+x,x,!d);}
  void restoreSnap(){Set<String>s=p.getStringSet("snapshot",new HashSet<>());if(s.isEmpty()){toast("Ingen snapshot");return;}for(String x:s)if(installed(x)&&!enabled(x))shell("pm enable --user 0 "+x,x,false);}
  void restoreAll(){for(String x:new HashSet<>(p.getStringSet("disabled",new HashSet<>())))shell("pm enable --user 0 "+x,x,false);}

  void shPage(){base("🔧 SHIZUKU TOOLS","Status och verifiering",true);note(shStatus());if(!shOk())btn("Begär behörighet",()->requestSh());btn("Testa Shizuku",()->shTest());if(shInstalled())btn("Öppna Shizuku",()->openPkg("moe.shizuku.privileged.api"));}
  void shTest(){if(!shOk()){requestSh();return;}new Thread(()->{String x;try{java.lang.Process q=proc("id");BufferedReader br=new BufferedReader(new InputStreamReader(q.getInputStream()));x=br.readLine();q.waitFor();}catch(Exception e){x="Test misslyckades";}final String y=x;runOnUiThread(()->new AlertDialog.Builder(this).setTitle("Shizuku-test").setMessage(y).setPositiveButton("OK",null).show());}).start();}
  void shell(String cmd,String pkg,boolean dis){if(!shOk()){requestSh();return;}new Thread(()->{try{java.lang.Process q=proc(cmd);int c=q.waitFor();runOnUiThread(()->{if(c==0){Set<String>s=new HashSet<>(p.getStringSet("disabled",new HashSet<>()));if(dis)s.add(pkg);else s.remove(pkg);p.edit().putStringSet("disabled",s).putString("last_pkg",pkg).putBoolean("last_disabled",dis).putString("last_change",(dis?"Avaktiverade ":"Återställde ")+pkg).apply();log((dis?"Avaktiverade ":"Återställde ")+pkg);toast("Klart");}else toast("Misslyckades: "+c);});}catch(Exception e){runOnUiThread(()->toast("Shizuku-kommandot misslyckades"));}}).start();}
  java.lang.Process proc(String cmd)throws Exception{Method m=Shizuku.class.getDeclaredMethod("newProcess",String[].class,String[].class,String.class);m.setAccessible(true);return(java.lang.Process)m.invoke(null,new Object[]{new String[]{"sh","-c",cmd},null,null});}

  void systemCheck(){String n=Build.FINGERPRINT+"|"+Build.VERSION.INCREMENTAL,o=p.getString("finger","");if(!o.isEmpty()&&!o.equals(n))p.edit().putBoolean("update",true).apply();p.edit().putString("finger",n).apply();}
  void afterUpdate(){base("🆕 EFTER SAMSUNG-UPPDATERING","Kontrollera återaktiverade paket",true);int n=0;StringBuilder b=new StringBuilder();for(String x:p.getStringSet("disabled",new HashSet<>()))if(installed(x)&&enabled(x)){n++;b.append("• ").append(x).append("\n");}note(n==0?"✅ Inga Toolbox-spårade paket verkar ha återaktiverats.":"⚠️ "+n+" tidigare avaktiverade paket är aktiva igen:\n"+b);note("Android "+Build.VERSION.RELEASE+"\nBuild "+Build.DISPLAY);btn("Öppna Debloat",()->debloat());btn("Markera kontroll klar",()->{p.edit().putBoolean("update",false).apply();show();});}

  void diag(){base("💾 BACKUP / DIAGNOSTIK","Kopiera eller spara Toolbox-status",true);note(report());btn("Kopiera rapport",()->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("diag",report()));toast("Kopierat");});btn("Spara TXT",()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("text/plain");i.putExtra(Intent.EXTRA_TITLE,"S23-Ultra-Toolbox-8.8-Backup.txt");startActivityForResult(i,EXP);});}
  String report(){return"S23 Ultra Toolbox 8.8\n"+Build.MANUFACTURER+" "+Build.MODEL+"\nAndroid "+Build.VERSION.RELEASE+" SDK "+Build.VERSION.SDK_INT+"\nBuild "+Build.DISPLAY+"\nBatteri "+level()+"%\nTemperatur "+fmt(temp())+"°C\nSpänning "+String.format(Locale.ROOT,"%.3f",volt()/1000.0)+" V\nRAM "+ram()+"%\nLedigt "+free()+" GB\n"+shStatus()+"\nProfil "+p.getString("profile","Standard")+"\nToolbox-avaktiverade "+p.getStringSet("disabled",new HashSet<>()).size()+"\nSenaste ändring: "+p.getString("last_change","Ingen")+"\nSenaste laddningsprov: "+p.getString("last_charge_test","Ingen")+"\nHealth "+score()+"/100";}
  protected void onActivityResult(int q,int z,Intent d){super.onActivityResult(q,z,d);if(q==EXP&&z==RESULT_OK&&d!=null&&d.getData()!=null)try(OutputStream o=getContentResolver().openOutputStream(d.getData())){o.write(report().getBytes(java.nio.charset.StandardCharsets.UTF_8));toast("Sparad");}catch(Exception e){toast("Kunde inte spara");}}

  void camera(){base("📸 CAMERA GUIDE 5.1","S23 Ultra scenprofiler",true);cam("Vardag","12 MP • 1x/3x • Auto HDR.");cam("Barn/djur","12 MP • bra ljus • 1x/3x • undvik nattläge vid rörelse.");cam("Mörkt rum","12 MP • 1x • nattläge • håll stilla.");cam("Måne","10x • stabilt stöd • sänk exponeringen.");cam("Konsert","3x/10x • sänk exponeringen • 4K30 i svagt ljus.");cam("Landskap","12 MP normalt. 200 MP bara i bra ljus och stilla motiv.");cam("Porträtt","3x ger ofta naturligare perspektiv.");cam("Video","4K60 i bra ljus/rörelse, 4K30 i svagare ljus.");btn("Starta kameran",()->{try{startActivity(new Intent("android.media.action.STILL_IMAGE_CAMERA"));}catch(Exception e){}});}
  void cam(String a,String b){sec(a);note(b);}
  void history(){base("🕘 HISTORIK","Senaste 100 Toolbox-åtgärder",true);note(p.getString("history","Ingen aktivitet ännu."));btn("Rensa historik",()->{p.edit().remove("history").apply();history();});}

  boolean writeOk(){if(Settings.System.canWrite(this))return true;startActivity(new Intent(Settings.ACTION_MANAGE_WRITE_SETTINGS,Uri.parse("package:"+getPackageName())));toast("Tillåt systeminställningar och prova igen");return false;}
  boolean installed(String x){try{getPackageManager().getPackageInfo(x,0);return true;}catch(Exception e){return false;}} boolean enabled(String x){try{return getPackageManager().getApplicationInfo(x,0).enabled;}catch(Exception e){return false;}}
  boolean shInstalled(){try{getPackageManager().getPackageInfo("moe.shizuku.privileged.api",0);return true;}catch(Exception e){return false;}} boolean shAlive(){try{return Shizuku.pingBinder();}catch(Throwable e){return false;}} boolean shOk(){try{return shAlive()&&Shizuku.checkSelfPermission()==PackageManager.PERMISSION_GRANTED;}catch(Throwable e){return false;}}
  String shStatus(){if(!shInstalled())return"❌ Shizuku ej installerad";if(!shAlive())return"⚠️ Shizuku-tjänsten ej igång";return shOk()?"✅ Shizuku aktiv och behörig":"🟡 Behörighet krävs";}
  void requestSh(){try{if(!shAlive()){openPkg("moe.shizuku.privileged.api");return;}Shizuku.requestPermission(SH);}catch(Throwable e){toast("Kunde inte begära behörighet");}}
  void open(String a){try{startActivity(new Intent(a));}catch(Exception e){}} boolean openPkg(String x){Intent i=getPackageManager().getLaunchIntentForPackage(x);if(i!=null){startActivity(i);return true;}return false;}
  void log(String s){String n=new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.getDefault()).format(new Date())+" • "+s,o=p.getString("history",""),a=n+(o.isEmpty()?"":"\n"+o);String[]x=a.split("\n");StringBuilder b=new StringBuilder();for(int i=0;i<Math.min(100,x.length);i++){if(i>0)b.append("\n");b.append(x[i]);}p.edit().putString("history",b.toString()).apply();}
  void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
