package se.smartoptimizer.toolbox;

import android.app.*;
import android.content.*;
import android.os.*;
import android.provider.Settings;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity102 extends MainActivity101 {
 @Override void show(){stopLive();base("S23 ULTRA TOOLBOX 10.2","Health Score • Smart Sessions • Safe Recovery",false);healthScore102();card("🚗 Starta jobbpass","Sparar startvärden och följer batteri/temperatur under körpasset.",()->jobSession102());card("📈 Historik & trender","Batteri, temperatur och laddstatus från sparade mätningar.",()->history102());card("🌡️ Thermal Guard 2.0","Smartare bedömning för GPS, DeX, kamera och laddning.",()->thermal102());card("🛡️ Debloat-profiler","Minimal • Rekommenderad • Avancerad med snapshot först.",()->debloatProfiles102());card("↩️ Ångra senaste ändringen","Öppnar säker återställning för senaste paketändringen.",()->undo102());card("🔄 Samsung Update Watch","Jämför och kontrollerar telefonen efter One UI-uppdatering.",()->update101());card("🔎 Djup appanalys","App Manager, paketstatus och säkerhetsbedömning.",()->appAnalysis102());card("⚡ Optimera nu","Säker kontroll utan aggressiv processrensning.",()->optimize101());card("🧠 Smart Advisor 8.0","Prioriterade rekommendationer.",()->advisor101());sec("Fler verktyg");card("🧯 Recovery Center 4.1","Snapshots och Android 16-säker återställning.",()->recovery101());card("🔋 Battery & Charging Lab","Laddning, batterihälsa och historik.",()->batteryLab100());card("🖥️ DeX-profil","Kontroll inför DeX-pass.",()->dexProfile101());card("📡 Live Monitor","Temperatur, RAM, batteri och laddning.",()->liveMonitor());card("🔧 Self-Test","Kontroll av Toolbox efter systemuppdatering.",()->selfTest100());card("📱 S23 Ultra Guide","Kamera, skärm, GPS, DeX och S Pen.",()->guide101());card("🕘 Toolbox-historik","Senaste åtgärder.",()->history());}
 int score102(){int s=100;float t=temp();if(t>=hotTemp())s-=25;else if(t>=warnTemp())s-=12;if(ram()>=95)s-=12;else if(ram()>=85)s-=5;if(free()<5)s-=20;else if(free()<10)s-=10;if(level()<15)s-=8;if(!shOk())s-=5;if(!signatureOk())s-=20;return Math.max(0,s);}
 void healthScore102(){int s=score102();String c=s>=90?"🟢":s>=70?"🟡":"🔴";note("TELEFONENS HÄLSOPOÄNG  "+c+" "+s+"/100\n🔋 "+level()+"% • 🌡️ "+fmt(temp())+"°C • 🧠 RAM "+ram()+"%\n💾 "+free()+" GB • "+(shOk()?"Shizuku OK":"Shizuku ej redo")+"\nTryck på Smart Advisor för orsaker och åtgärder.");}
 void jobSession102(){base("🚗 SMART JOBBPASS","GPS • temperatur • batteri",true);boolean active=p.getBoolean("job_session102",false);if(!active){note("Startar ett mätpass utan att ändra känsliga systeminställningar.");btn("▶ Starta jobbpass",()->{p.edit().putBoolean("job_session102",true).putInt("job_bat102",level()).putFloat("job_temp102",temp()).putLong("job_time102",System.currentTimeMillis()).apply();saveBatterySample101();toast("Jobbpass startat");jobSession102();});}else{long mins=(System.currentTimeMillis()-p.getLong("job_time102",System.currentTimeMillis()))/60000;int start=p.getInt("job_bat102",level());float st=p.getFloat("job_temp102",temp());note("🟢 Jobbpass aktivt\nTid: "+mins+" min\nBatteri: "+start+"% → "+level()+"%\nTemperatur: "+fmt(st)+"°C → "+fmt(temp())+"°C");btn("📍 Google Maps",()->launchPkg100("com.google.android.apps.maps","Google Maps"));btn("⏹ Avsluta och spara sammanfattning",()->{String r="Jobbpass "+mins+" min • batteri "+start+"→"+level()+"% • temp "+fmt(st)+"→"+fmt(temp())+"°C";p.edit().putBoolean("job_session102",false).putString("last_job102",r).apply();log(r);saveBatterySample101();toast("Jobbpass sparat");jobSession102();});}String last=p.getString("last_job102","");if(!last.isEmpty())note("Senaste: "+last);}
 void history102(){saveBatterySample101();base("📈 HISTORIK & TRENDER","Senaste mätningarna",true);String h=p.getString("battery_history101","");note(h.isEmpty()?"Ingen historik ännu.":h);note("Toolbox sparar lokala mätpunkter. Fler mätningar ger bättre bild av temperatur och laddning över tid.");btn("Battery & Charging Lab",()->batteryLab100());btn("Thermal Guard 2.0",()->thermal102());}
 void thermal102(){base("🌡️ THERMAL GUARD 2.0","Dynamisk belastningsbedömning",true);float t=temp();boolean charging=status()==BatteryManager.BATTERY_STATUS_CHARGING;int warn=warnTemp();int hot=hotTemp();String context=charging?"Laddning":"Normal användning";String state=t>=hot?"🔴 Hög":t>=warn?"🟡 Varm":"🟢 Normal";note("Läge: "+context+"\nTemperatur: "+fmt(t)+"°C • "+state+"\n"+(charging&&t>=warn?"Vid laddning och hög värme: undvik samtidigt tung GPS, DeX eller kamera.":t>=warn?"Följ temperaturen under längre GPS/DeX-pass.":"Bra temperatur för normal belastning."));btn("Live Monitor",()->liveMonitor());btn("Temperaturgränser",()->thermalAlerts());}
 void debloatProfiles102(){base("🛡️ DEBLOAT-PROFILER","Förhandsvisning • Snapshot • Recovery",true);note("Minimal: bara tydligt valfria paket.\nRekommenderad: Toolbox normala säkra urval.\nAvancerad: visar även paket märkta Försiktig, men ändrar inget utan ditt val.");btn("Minimal – förhandsvisa",()->profilePreview102("Minimal"));btn("Rekommenderad – förhandsvisa",()->profilePreview102("Rekommenderad"));btn("Avancerad – förhandsvisa",()->profilePreview102("Avancerad"));btn("Öppna Smart Debloat",()->debloat());}
 void profilePreview102(String mode){saveRecoverySnapshot100();base("🛡️ "+mode.toUpperCase(Locale.getDefault()),"Recovery Snapshot sparad",true);int n=0;for(String[]a:PK)if(installed(a[1])){boolean include=mode.equals("Avancerad")||mode.equals("Rekommenderad")&&!a[2].equals("Försiktig")||mode.equals("Minimal")&&a[2].equals("Säker");if(include){note("• "+a[0]+" — "+a[2]+"\n"+effectiveState95(a[1]));n++;}}sec(n+" appar i förhandsvisningen");note("Ingen app ändrades av förhandsvisningen.");btn("Fortsätt till Smart Debloat",()->debloat());}
 void undo102(){base("↩️ ÅNGRA SENASTE ÄNDRING","Säker återställning",true);note("Toolbox använder Recovery Assistant och sparad paketstatus. Android 16-skydd kringgås inte; om shell blockeras öppnas appens systeminställningar.");btn("Öppna Recovery Assistant",()->recoveryAssistant95());btn("Visa Recovery Snapshot",()->recovery101());btn("Visa historik",()->history());}
 void appAnalysis102(){base("🔎 DJUP APPANALYS","Paket • status • risknivå",true);note("Använd App Manager för alla installerade appar. Smart Debloat visar dessutom Toolbox säkerhetsnivå och effektiv enabled-status för kända paket.");btn("App Manager",()->apps89());btn("Smart Debloat 8.1",()->debloat());btn("App Change Watch",()->appChangeWatch());}
}
