package se.smartoptimizer.toolbox;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.os.*;
import android.view.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity103 extends MainActivity102 {
 @Override void show(){stopLive();base("S23 ULTRA TOOLBOX 10.3","Quality Update • Smart Sessions • Recovery",false);healthScore103();card("🚗 Jobbpass 2.0","Körtid, batteriförbrukning/timme och temperaturtopp.",()->job103());card("📊 Grafer & historik","Visuella grafer för batteri och temperatur.",()->graphs103());card("🔋 Laddningsanalys","Jämför laddsessioner, hastighet och temperaturökning.",()->chargeLab103());card("↩️ Ångra senaste Toolbox-ändring","Återställ exakt senaste Debloat-ändringen när Android tillåter det.",()->undo103());card("🛡️ Samsung Debloat Guide","Visar vad paket kan påverka på S23 Ultra.",()->samsungGuide103());card("🌡️ Thermal Guard 2.1","Belastningsråd för GPS, DeX, kamera och laddning.",()->thermal102());card("🔄 Samsung Update Watch","Kontroll efter One UI / Android-uppdatering.",()->update101());sec("Snabbval");card("⚡ Optimera nu","Säker kontroll utan aggressiv processrensning.",()->optimize101());card("🧠 Smart Advisor 8.0","Prioriterade rekommendationer.",()->advisor101());card("🛡️ Smart Debloat 8.2","Snapshot + Undo före varje ändring.",()->debloat());card("🧯 Recovery Center 4.2","Snapshots, Undo och Android 16-säker återställning.",()->recovery103());sec("Fler verktyg");card("🚗 Jobb / GPS-läge","Förkontroll inför navigation.",()->jobGps101());card("🔋 Battery & Charging Lab","Batterihälsa och laddverktyg.",()->batteryLab100());card("🖥️ DeX-profil","Kontroll inför DeX.",()->dexProfile101());card("📡 Live Monitor","Temperatur, RAM, batteri och laddning.",()->liveMonitor());card("💾 Storage Analyzer","Lagringsanalys.",()->storageAnalyzer());card("📦 App Manager","Installerade appar.",()->apps89());card("🔧 Self-Test","Systemkontroll.",()->selfTest100());card("📱 S23 Ultra Guide","Kamera, skärm, GPS, DeX och S Pen.",()->guide101());card("🔧 Shizuku Tools",shStatus(),()->shPage());card("🕘 Historik","Toolbox-åtgärder.",()->history());}

 int score103(){int s=100;float t=temp(),baseRam=p.getFloat("base_ram",ram());if(t>=hotTemp())s-=25;else if(t>=warnTemp())s-=10;if(ram()>=97&&ram()>baseRam+15)s-=10;else if(ram()>=95&&ram()>baseRam+10)s-=5;if(free()<5)s-=20;else if(free()<10)s-=10;if(level()<10)s-=8;if(!shOk())s-=5;if(!signatureOk())s-=20;return Math.max(0,s);}
 void healthScore103(){int s=score103();String c=s>=90?"🟢":s>=70?"🟡":"🔴";note(c+" HÄLSOPOÄNG 2.0  "+s+"/100\n🔋 "+level()+"% • 🌡️ "+fmt(temp())+"°C • 🧠 RAM "+ram()+"%\n💾 "+free()+" GB • "+(shOk()?"Shizuku OK":"Shizuku ej redo")+"\nRAM bedöms mot telefonens lokala baslinje, inte bara en fast procentsats.");}

 void job103(){base("🚗 JOBBPASS 2.0","Körtid • förbrukning • temperatur",true);boolean on=p.getBoolean("job103_on",false);if(!on){String last=p.getString("job103_last","");if(!last.isEmpty())note("Senaste pass:\n"+last);btn("▶ Starta jobbpass",()->{p.edit().putBoolean("job103_on",true).putLong("job103_t",System.currentTimeMillis()).putInt("job103_b",level()).putFloat("job103_temp",temp()).putFloat("job103_max",temp()).apply();saveBatterySample101();toast("Jobbpass startat");job103();});return;}long ms=Math.max(1,System.currentTimeMillis()-p.getLong("job103_t",System.currentTimeMillis()));double hours=ms/3600000d;int b0=p.getInt("job103_b",level()),used=Math.max(0,b0-level());float startT=p.getFloat("job103_temp",temp()),mx=Math.max(p.getFloat("job103_max",temp()),temp());p.edit().putFloat("job103_max",mx).apply();double ph=used/hours;note("🟢 Aktivt • "+(ms/60000)+" min\n🔋 "+b0+"% → "+level()+"% • "+String.format(Locale.ROOT,"%.1f",ph)+" %/tim\n🌡️ Start "+fmt(startT)+"°C • topp "+fmt(mx)+"°C");btn("📍 Spara kontrollpunkt",()->{float m=Math.max(p.getFloat("job103_max",temp()),temp());p.edit().putFloat("job103_max",m).apply();saveBatterySample101();toast("Kontrollpunkt sparad");job103();});btn("📍 Öppna Google Maps",()->launchPkg100("com.google.android.apps.maps","Google Maps"));btn("⏹ Avsluta jobbpass",()->{long dur=Math.max(1,System.currentTimeMillis()-p.getLong("job103_t",System.currentTimeMillis()));double h=dur/3600000d;int start=p.getInt("job103_b",level());int drain=Math.max(0,start-level());float max=Math.max(p.getFloat("job103_max",temp()),temp());String r=(dur/60000)+" min • "+start+"→"+level()+"% • "+String.format(Locale.ROOT,"%.1f",drain/h)+" %/tim • max "+fmt(max)+"°C";p.edit().putBoolean("job103_on",false).putString("job103_last",r).apply();log("Jobbpass 2.0: "+r);saveBatterySample101();job103();});}

 void graphs103(){saveBatterySample101();base("📊 GRAFER & HISTORIK","Senaste lokala mätpunkterna",true);ArrayList<Float>b=new ArrayList<>(),t=new ArrayList<>();String raw=p.getString("battery_history101","");for(String line:raw.split("\n")){try{String[]x=line.split(" • ");if(x.length>=3){b.add(Float.parseFloat(x[1].replace("%","")));t.add(Float.parseFloat(x[2].replace("°C","")));}}catch(Exception e){}}Collections.reverse(b);Collections.reverse(t);sec("🔋 Batteri %");addChart103(b,0,100,"%");sec("🌡️ Temperatur °C");addChart103(t,20,50,"°C");if(b.size()<3)note("Spara några fler mätningar för en tydligare trend.");btn("Spara mätpunkt nu",()->{saveBatterySample101();graphs103();});}
 void addChart103(ArrayList<Float>v,float lo,float hi,String unit){if(v.isEmpty()){note("Ingen data ännu.");return;}MetricView103 m=new MetricView103(this,v,lo,hi);root.addView(m,new android.widget.LinearLayout.LayoutParams(-1,260));float min=Collections.min(v),max=Collections.max(v),last=v.get(v.size()-1);note("Min "+fmt(min)+unit+" • Max "+fmt(max)+unit+" • Senast "+fmt(last)+unit+" • "+v.size()+" punkter");}
 class MetricView103 extends View{ArrayList<Float>v;float lo,hi;Paint p1=new Paint(1),grid=new Paint(1);MetricView103(Context c,ArrayList<Float>x,float a,float b){super(c);v=x;lo=a;hi=b;p1.setColor(GREEN);p1.setStrokeWidth(5);p1.setStyle(Paint.Style.STROKE);grid.setColor(Color.DKGRAY);grid.setStrokeWidth(2);}protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight(),pad=18;c.drawLine(pad,h-pad,w-pad,h-pad,grid);c.drawLine(pad,pad,pad,h-pad,grid);if(v.size()<2)return;Path path=new Path();for(int i=0;i<v.size();i++){float x=pad+(w-2*pad)*i/(v.size()-1f);float n=Math.max(lo,Math.min(hi,v.get(i)));float y=h-pad-(h-2*pad)*(n-lo)/(hi-lo);if(i==0)path.moveTo(x,y);else path.lineTo(x,y);}c.drawPath(path,p1);}}

 void chargeLab103(){base("🔋 LADDNINGSANALYS","Sessioner • hastighet • temperatur",true);boolean on=p.getBoolean("chg103_on",false);if(!on){String hist=p.getString("chg103_hist","");if(!hist.isEmpty())note("Senaste sessioner:\n"+hist);btn("▶ Starta laddsession",()->{p.edit().putBoolean("chg103_on",true).putLong("chg103_t",System.currentTimeMillis()).putInt("chg103_b",level()).putFloat("chg103_temp",temp()).apply();toast("Laddsession startad");chargeLab103();});}else{long ms=Math.max(1,System.currentTimeMillis()-p.getLong("chg103_t",System.currentTimeMillis()));int b0=p.getInt("chg103_b",level()),gain=level()-b0;float t0=p.getFloat("chg103_temp",temp());double ph=gain/(ms/3600000d);note("🟢 Session aktiv • "+(ms/60000)+" min\n🔋 "+b0+"% → "+level()+"% • "+String.format(Locale.ROOT,"%.1f",ph)+" %/tim\n🌡️ "+fmt(t0)+"°C → "+fmt(temp())+"°C\nStatus: "+charge());btn("⏹ Avsluta och spara",()->finishCharge103());}btn("Battery Health",()->batteryHealth());btn("Charging Test Pro",()->battery89());}
 void finishCharge103(){long ms=Math.max(1,System.currentTimeMillis()-p.getLong("chg103_t",System.currentTimeMillis()));int b0=p.getInt("chg103_b",level()),gain=level()-b0;float t0=p.getFloat("chg103_temp",temp()),dt=temp()-t0;double ph=gain/(ms/3600000d);String row=new SimpleDateFormat("MM-dd HH:mm",Locale.getDefault()).format(new Date())+" • "+(ms/60000)+" min • "+b0+"→"+level()+"% • "+String.format(Locale.ROOT,"%.1f",ph)+" %/tim • ΔT "+(dt>=0?"+":"")+fmt(dt)+"°C";String old=p.getString("chg103_hist","");String all=row+(old.isEmpty()?"":"\n"+old);String[]ls=all.split("\n");StringBuilder out=new StringBuilder();for(int i=0;i<Math.min(8,ls.length);i++){if(i>0)out.append('\n');out.append(ls[i]);}p.edit().putBoolean("chg103_on",false).putString("chg103_hist",out.toString()).apply();log("Laddsession: "+row);chargeLab103();}

 @Override void debloat(){base("🛡️ SMART DEBLOAT 8.2","S23 Ultra • Snapshot • Undo • Android 16 Recovery",true);note(shStatus());note("Recovery Snapshot sparas före varje ändring. Senaste Debloat-åtgärden kan ångras separat.");btn("📘 Samsung Debloat Guide",()->samsungGuide103());btn("✨ Rekommenderad säker batch",()->recommended());String last="";for(String[]a:PK)if(installed(a[1])){if(!a[3].equals(last)){sec(a[3]);last=a[3];}boolean en=enabled(a[1]);String risk=a[2].equals("Försiktig")?"⚠️ Försiktig":a[2].equals("Säker")?"✅ Säker":"ℹ️ Valfri";note(a[0]+" • "+risk+"\n"+a[4]+"\nPåverkan: "+impact103(a[1])+"\nStatus: "+effectiveState95(a[1]));if(en)btn("Avaktivera "+a[0],()->change103(a,true));else btn("Återställ "+a[0],()->change103(a,false));}}
 void change103(String[]a,boolean disable){saveRecoverySnapshot100();p.edit().putString("undo103_pkg",a[1]).putString("undo103_name",a[0]).putBoolean("undo103_was_enabled",!disable).putLong("undo103_time",System.currentTimeMillis()).apply();if(disable)shell("pm disable-user --user 0 "+a[1],a[1],true);else shell("pm enable --user 0 "+a[1],a[1],false);log((disable?"Avaktivera: ":"Återställ: ")+a[0]);}
 void undo103(){base("↩️ ÅNGRA SENASTE ÄNDRING","Debloat Undo",true);String pkg=p.getString("undo103_pkg","");if(pkg.isEmpty()){note("Ingen separat 10.3-ändring finns att ångra ännu.");btn("Recovery Assistant",()->recoveryAssistant95());return;}String name=p.getString("undo103_name",pkg);boolean was=p.getBoolean("undo103_was_enabled",true);note("Senaste ändring: "+name+"\nTid: "+new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.getDefault()).format(new Date(p.getLong("undo103_time",0)))+"\nTidigare status: "+(was?"Aktiv":"Avaktiverad")+"\nNu: "+effectiveState95(pkg));btn("↩️ Ångra nu",()->{saveRecoverySnapshot100();if(was)shell("pm enable --user 0 "+pkg,pkg,false);else shell("pm disable-user --user 0 "+pkg,pkg,true);p.edit().remove("undo103_pkg").apply();log("Undo 10.3: "+name);});btn("Recovery Assistant",()->recoveryAssistant95());}
 void recovery103(){base("🧯 RECOVERY CENTER 4.2","Snapshot • Undo • Android 16",true);String s=p.getString("recovery_snapshot100","");note(s.isEmpty()?"Ingen snapshot sparad.":"Snapshot: "+p.getString("recovery_snapshot_time100","okänd")+" • "+snapshotSummary100(s));btn("↩️ Ångra senaste Debloat-ändring",()->undo103());btn("Spara ny Recovery Snapshot",()->saveRecoverySnapshot100());btn("Recovery Assistant",()->recoveryAssistant95());btn("Toolbox-historik",()->history());}

 String impact103(String pkg){if(pkg.contains("bixby"))return"Bixby och röstfunktioner";if(pkg.contains("oneconnect"))return"SmartThings, anslutna enheter och vissa DeX-flöden";if(pkg.contains("shealth"))return"Samsung Health och vissa Galaxy Watch-funktioner";if(pkg.contains("scloud"))return"Samsung Cloud, synk och backup";if(pkg.contains("gearhead"))return"Android Auto";if(pkg.contains("tachyon"))return"Google Meet";if(pkg.contains("arzone"))return"AR Zone/AR-effekter, inte grundkameran";if(pkg.contains("spage"))return"Samsung Free-panelen";if(pkg.contains("kids"))return"Samsung Kids";if(pkg.contains("voc"))return"Samsung Members/supportdiagnostik";if(pkg.contains("youtube.music"))return"YouTube Music";if(pkg.contains("subscriptions.red"))return"Google One och dess appfunktioner";if(pkg.contains("facebook"))return"Meta/Facebook bakgrundskomponenter";return"Den angivna appens egna funktioner";}
 void samsungGuide103(){base("🛡️ SAMSUNG DEBLOAT GUIDE","S23 Ultra-konsekvenser före ändring",true);for(String[]a:PK)if(installed(a[1]))note((a[2].equals("Försiktig")?"⚠️ ":a[2].equals("Säker")?"✅ ":"ℹ️ ")+a[0]+"\n"+impact103(a[1])+"\nRisk: "+a[2]);note("Toolbox listar inte kärnpaket för telefoni, System UI, kamera, Knox eller launcher i den rekommenderade säkra batchen.");}
}
