package se.smartoptimizer.toolbox;

import android.app.*;
import android.os.*;
import java.util.*;

public class MainActivity105 extends MainActivity103 {
 @Override void show(){stopLive();base("S23 ULTRA TOOLBOX 10.5 STABLE","Health • Jobb • Recovery • Samsung",false);healthScore105();card("⚡ Optimera nu","Säker kontroll och prioriterade åtgärder.",()->optimize101());card("🚗 Jobbpass Pro 2.0","Körtid, batteriförbrukning/timme och temperaturtopp.",()->job103());card("📊 Trend Dashboard 2.0","Riktiga batteri- och temperaturgrafer från lokala mätningar.",()->graphs103());card("🔋 Laddningsanalys 2.0","Spara laddsessioner, hastighet och temperaturökning.",()->chargeLab103());card("↩️ Undo & Recovery 2.0","Ångra senaste Debloat-ändring och använd Recovery Snapshot.",()->recovery103());card("🛡️ Samsung Debloat Guide 2.0","Visar vad varje känt paket kan påverka på S23 Ultra.",()->samsungGuide103());sec("Favoriter");card("🧠 Smart Advisor 8.1","Förbättrad hälsobedömning utan onödig RAM-rensning.",()->advisor105());card("🌡️ Thermal Guard 2.1","GPS, DeX, kamera och laddning.",()->thermal102());card("🖥️ DeX-profil","Kontroll inför DeX-pass.",()->dexProfile101());card("🔄 Samsung Update Watch","Kontroll efter One UI-uppdateringar.",()->update101());sec("Avancerat");card("🛡️ Smart Debloat 8.2","Snapshot + separat Undo före varje ändring.",()->debloat());card("📦 App Manager","Installerade appar och paketstatus.",()->apps89());card("📡 Live Monitor","Temperatur, RAM och batteri.",()->liveMonitor());card("💾 Storage Analyzer","Lagringsanalys.",()->storageAnalyzer());card("🔧 Self-Test","Kontroll av Toolbox-funktioner.",()->selfTest100());card("🔧 Shizuku Tools",shStatus(),()->shPage());card("📱 S23 Ultra Guide","Kamera, skärm, GPS, DeX och S Pen.",()->guide101());card("🕘 Historik","Senaste Toolbox-åtgärder.",()->history());}
 int score105(){int s=100;float t=temp(),baseRam=p.getFloat("base_ram",ram());if(t>=hotTemp())s-=25;else if(t>=warnTemp())s-=10;if(free()<5)s-=20;else if(free()<10)s-=10;if(ram()>=97&&ram()>baseRam+15)s-=10;else if(ram()>=95&&ram()>baseRam+10)s-=5;if(level()<10)s-=8;if(!shOk())s-=4;if(!signatureOk())s-=20;return Math.max(0,s);}
 void healthScore105(){int s=score105();String c=s>=90?"🟢 BRA":s>=70?"🟡 KONTROLLERA":"🔴 ÅTGÄRDA";note("HÄLSOPOÄNG 2.0  "+s+"/100 • "+c+"\n🔋 "+level()+"%   🌡️ "+fmt(temp())+"°C   🧠 RAM "+ram()+"%\n💾 "+free()+" GB   🔧 "+(shOk()?"Shizuku OK":"Shizuku ej redo")+"\nRAM bedöms mot telefonens lokala baslinje eftersom Android normalt använder ledigt minne som cache.");}
 void advisor105(){base("🧠 SMART ADVISOR 8.1","Hälsa utan onödig RAM-rensning",true);note("Poäng: "+score105()+"/100");if(temp()>=warnTemp())note("🌡️ Temperatur är viktigare än normal Android-cache. Följ Thermal Guard.");if(free()<10)note("💾 Ledigt utrymme är lågt: "+free()+" GB.");float br=p.getFloat("base_ram",ram());if(ram()>=97&&ram()>br+15)note("🧠 RAM ligger både mycket högt och tydligt över din normala baslinje.");if(!shOk())note("🔧 Shizuku behövs bara för avancerade paketåtgärder.");if(score105()>=90)note("✅ Inget viktigt behöver åtgärdas.");btn("Optimera nu",()->optimize101());btn("Trend Dashboard",()->graphs103());}
}
