package se.smartoptimizer.toolbox;

import android.app.*;
import android.os.*;
import android.content.*;
import android.content.pm.*;
import android.graphics.*;
import android.net.Uri;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.security.MessageDigest;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity89 extends MainActivity {
  final int BACKUP_OUT=8902, BACKUP_IN=8903;
  final String EXPECTED_CERT="85:8B:14:23:50:1A:E5:71:79:63:BA:71:40:20:A4:9F:9D:01:E1:15:65:99:77:CD:66:F0:98:66:AE:0D:70:81";

  @Override void show(){base("S23 ULTRA TOOLBOX 8.9","Dashboard 5.0 • Self Test • Battery Health • Backup",false);dashboard89();if(p.getBoolean("update",false))card("🆕 Efter Samsung-uppdatering","Kontrollera om paket eller inställningar ändrats.",()->afterUpdate());card("🧠 Smart Advisor 5.0","Lokala baslinjer + tydligare prioritering.",()->advisor89());card("🛡️ Smart Debloat 7.1","Risk, leverantör, beroendevarning och failsafe.",()->debloat());card("📦 App Manager 2.1","Sök, filtrera och se nyligen uppdaterade appar.",()->apps89());card("🌡️ Thermal Watch 4.1","Trend, historik och temperaturgraf.",()->thermal89());card("🔋 Battery Health","Rapporterad batterihälsa och sensorer utan påhittad procent.",()->batteryHealth());card("⚡ Charging Test Pro 2.0","Namngivna tester och jämförelse av laddare.",()->battery89());card("🚗 GPS/Jobbläge Pro","Skärm vaken, rotation och GPS-snabbval.",()->profiles89());card("🖥️ DeX Center 2.1","Extern skärm, temperatur och snabbval.",()->dex());card("🧪 Toolbox Self Test","Signering, Shizuku, sensorer och behörigheter.",()->selfTest());card("🧯 Recovery Center 2.1","Ångra senaste och se exakt vad Toolbox ändrat.",()->recovery());card("💾 Backup / Restore","Exportera och importera Toolbox-data säkert.",()->backupPage());card("⚙️ Quick Center","Snabbvägar till viktiga systeminställningar.",()->quickCenter());card("🔧 Shizuku Tools",shStatus(),()->shPage());card("📸 Camera Guide 5.2","Fler praktiska råd för S23 Ultra-kameran.",()->camera89());card("🕘 Historik","Senaste Toolbox-åtgärder.",()->history());}

  void dashboard89(){LinearLayout a=new LinearLayout(this);a.setOrientation(LinearLayout.HORIZONTAL);a.addView(chip("🌡️ "+fmt(temp())+"°C\n"+tname()));a.addView(chip("🔋 "+level()+"%\n"+charge()));root.addView(a);LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.HORIZONTAL);b.addView(chip("🧠 RAM "+ram()+"%\n"+(ram()>90?"Hög":"Normal")));b.addView(chip("💾 "+free()+" GB\nledigt"));root.addView(b);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.HORIZONTAL);c.addView(chip("🔧 Shizuku\n"+(shOk()?"Behörig":"Ej redo")));c.addView(chip("🔐 Signering\n"+(signatureOk()?"Verifierad":"Kontrollera")));root.addView(c);note("Health "+score()+"/100 • Profil: "+p.getString("profile","Standard")+" • 🛡️ "+safe()+" säkra förslag");}

  int batteryHealthCode(){Intent i=bi();return i==null?0:i.getIntExtra(BatteryManager.EXTRA_HEALTH,0);}String batteryTech(){Intent i=bi();String s=i==null?null:i.getStringExtra(BatteryManager.EXTRA_TECHNOLOGY);return s==null?"Okänd":s;}String batteryHealthName(){switch(batteryHealthCode()){case BatteryManager.BATTERY_HEALTH_GOOD:return"Bra";case BatteryManager.BATTERY_HEALTH_OVERHEAT:return"Överhettat";case BatteryManager.BATTERY_HEALTH_DEAD:return"Dåligt";case BatteryManager.BATTERY_HEALTH_OVER_VOLTAGE:return"Överspänning";case BatteryManager.BATTERY_HEALTH_COLD:return"För kallt";default:return"Okänd/ej rapporterad";}}

  void advisor89(){base("🧠 SMART ADVISOR 5.0","Lokala baslinjer + prioriterade råd",true);float bt=p.getFloat("base_temp",temp()),br=p.getFloat("base_ram",ram());note("Nu: "+fmt(temp())+"°C • RAM "+ram()+"% • "+free()+" GB ledigt\nBaslinje: "+fmt(bt)+"°C • RAM "+fmt(br)+"%");sec("Prioriterade råd");int n=0;if(batteryHealthCode()==BatteryManager.BATTERY_HEALTH_OVERHEAT||temp()>=43)note(++n+". 🔥 Prioritet hög: telefonen är mycket varm. Pausa tung belastning och laddning tills den svalnat.");else if(temp()>bt+4||temp()>=40)note(++n+". 🌡️ Varmare än normalt. Vänta med benchmark/gaming.");if(level()<20&&!"Laddar".equals(charge()))note(++n+". 🔋 Låg batterinivå. Ladda före längre GPS/DeX-pass.");if(ram()>br+18)note(++n+". 🧠 RAM ligger tydligt över din normala nivå. Android får först hantera minnet själv.");if(free()<20)note(++n+". 💾 Frigör lagring före större uppdateringar.");if(!shOk())note(++n+". 🔧 Starta Shizuku för Debloat-funktionerna.");if(safe()>0)note(++n+". 🛡️ "+safe()+" säkra paket kan granskas i Debloat.");if(n==0)note("✅ Inga viktiga åtgärder just nu.");btn("Öppna Battery Health",()->batteryHealth());btn("Öppna Debloat",()->debloat());log("Advisor 5.0: Health "+score());}

  void apps89(){base("📦 APP MANAGER 2.1","Sök • system • användare • Samsung • Google • nyligen uppdaterade",true);EditText e=new EditText(this);e.setHint("Sök app eller paket…");e.setTextColor(Color.WHITE);e.setHintTextColor(Color.GRAY);root.addView(e);btn("Alla",()->appList(e.getText().toString(),0));btn("Systemappar",()->appList(e.getText().toString(),1));btn("Användarappar",()->appList(e.getText().toString(),2));btn("Avaktiverade",()->appList(e.getText().toString(),3));btn("Samsung",()->appList(e.getText().toString(),4));btn("Google",()->appList(e.getText().toString(),5));btn("Nyligen uppdaterade",()->recentApps(e.getText().toString()));}
  void recentApps(String q){try{PackageManager pm=getPackageManager();ArrayList<ApplicationInfo>m=new ArrayList<>();String z=q.toLowerCase(Locale.ROOT);for(ApplicationInfo a:pm.getInstalledApplications(0)){String n=""+pm.getApplicationLabel(a);if(z.isEmpty()||n.toLowerCase().contains(z)||a.packageName.toLowerCase().contains(z))m.add(a);}m.sort((a,b)->Long.compare(lastUpdate(b.packageName),lastUpdate(a.packageName)));int n=Math.min(100,m.size());String[]x=new String[n];for(int i=0;i<n;i++)x[i]=pm.getApplicationLabel(m.get(i))+"\n"+date(lastUpdate(m.get(i).packageName))+" • "+m.get(i).packageName;new AlertDialog.Builder(this).setTitle("Nyligen uppdaterade").setItems(x,(d,i)->inspect(m.get(i).packageName)).setNegativeButton("Stäng",null).show();}catch(Exception e){toast("Kunde inte läsa applistan");}}
  long lastUpdate(String x){try{return getPackageManager().getPackageInfo(x,0).lastUpdateTime;}catch(Exception e){return 0;}}String date(long t){return new SimpleDateFormat("yyyy-MM-dd",Locale.getDefault()).format(new Date(t));}

  void thermal89(){base("🌡️ THERMAL WATCH 4.1","Trend • min • max • medel • graf",true);float[]s=stats("temps");note("Aktuellt: "+fmt(temp())+"°C • "+tname());if(s[3]>0)note("Min "+fmt(s[0])+"°C • Max "+fmt(s[1])+"°C • Medel "+fmt(s[2])+"°C • "+(int)s[3]+" mätningar\nTrend: "+trend());root.addView(new TempGraph(this,parseRecent("temps",60)),new LinearLayout.LayoutParams(-1,240));btn("Starta 1 minut",()->startTemp(12));btn("Starta 5 minuter",()->startTemp(60));btn("Starta 15 minuter",()->startTemp(180));btn("Starta 30 minuter",()->startTemp(360));sec("Senaste 20");note(latest("temps",20));btn("Rensa temperaturhistorik",()->{p.edit().remove("temps").apply();thermal89();});}
  class TempGraph extends View{float[]v;Paint a=new Paint(1),g=new Paint(1);TempGraph(Context c,float[]x){super(c);v=x;a.setColor(GREEN);a.setStrokeWidth(4);g.setColor(Color.DKGRAY);g.setStrokeWidth(1);setBackgroundColor(CARD);}protected void onDraw(Canvas c){super.onDraw(c);int w=getWidth(),hh=getHeight();for(int i=1;i<4;i++)c.drawLine(0,hh*i/4f,w,hh*i/4f,g);if(v.length<2)return;float mi=999,ma=-999;for(float x:v){mi=Math.min(mi,x);ma=Math.max(ma,x);}if(ma-mi<1)ma=mi+1;Path pth=new Path();for(int i=0;i<v.length;i++){float x=w*i/(float)(v.length-1),y=hh-(v[i]-mi)/(ma-mi)*hh;if(i==0)pth.moveTo(x,y);else pth.lineTo(x,y);}c.drawPath(pth,a);}}
  float[]parseRecent(String k,int max){String[]a=p.getString(k,"").split("\n");int n=Math.min(max,a.length);float[]out=new float[n];int z=0;for(int i=n-1;i>=0;i--)try{out[z++]=Float.parseFloat(a[i].substring(a[i].lastIndexOf("•")+1).trim());}catch(Exception e){}return z==out.length?out:Arrays.copyOf(out,z);}

  void batteryHealth(){base("🔋 BATTERY HEALTH","Rapporterade Android-värden – inga påhittade procenttal",true);long cc=0;try{cc=((BatteryManager)getSystemService(BATTERY_SERVICE)).getLongProperty(BatteryManager.BATTERY_PROPERTY_CHARGE_COUNTER);}catch(Exception e){}String counter=cc>0?String.format(Locale.ROOT,"%.0f mAh",cc/1000.0):"Ej tillgänglig";note("Android-hälsa: "+batteryHealthName()+"\nTeknik: "+batteryTech()+"\nNivå: "+level()+"%\nTemperatur: "+fmt(temp())+"°C\nSpänning: "+String.format(Locale.ROOT,"%.3f",volt()/1000.0)+" V\nLaddningsräknare just nu: "+counter+"\nStatus: "+charge());note("Toolbox visar inte en uppskattad 'battery health %' om systemet inte rapporterar ett tillförlitligt värde.");btn("Öppna Batteriinställningar",()->open(Settings.ACTION_BATTERY_SAVER_SETTINGS));btn("Charging Test Pro",()->battery89());}

  void battery89(){base("⚡ CHARGING TEST PRO 2.0","Namngivna tester • effekt • temperatur • jämförelse",true);long u=ua();double v=volt()/1000.0,w=v*Math.abs(u)/1000000.0;String cur=Math.abs(u)<1000?"Ingen mätbar ström just nu":String.format(Locale.ROOT,"%.0f mA",u/1000.0);note("Batteri: "+level()+"%\nTemperatur: "+fmt(temp())+"°C\nSpänning: "+String.format(Locale.ROOT,"%.3f",v)+" V\nStröm: "+cur+"\nUppskattad effekt: "+String.format(Locale.ROOT,"%.2f",w)+" W\nStatus: "+charge());String tests=p.getString("charge_tests","");if(!tests.isEmpty()){sec("Sparade tester");note(tests);}note("Effekten är en Android-sensoruppskattning, inte laddarens märkta watt.");btn("Nytt 1 min test",()->askChargeName(12));btn("Nytt 5 min test",()->askChargeName(60));btn("Nytt 10 min test",()->askChargeName(120));btn("Rensa sparade tester",()->{p.edit().remove("charge_tests").apply();battery89();});}
  void askChargeName(int n){EditText e=new EditText(this);e.setHint("t.ex. Samsung 45 W / Bil / Powerbank");new AlertDialog.Builder(this).setTitle("Namn på testet").setView(e).setNegativeButton("Avbryt",null).setPositiveButton("Starta",(d,w)->startNamedPower(n,e.getText().toString().trim())).show();}
  void startNamedPower(int n,String name){stop();p.edit().remove("watts").remove("chargeTemps").apply();final int[]c={0};final String nm=name.isEmpty()?"Laddtest "+new SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date()):name;watch=new Runnable(){public void run(){float w=(float)(volt()/1000.0*Math.abs(ua())/1000000.0);save("watts",w,240);save("chargeTemps",temp(),240);if(++c[0]<n)h.postDelayed(this,5000);else{watch=null;float[]s=stats("watts"),t=stats("chargeTemps");String out=nm+" • "+new SimpleDateFormat("MM-dd HH:mm",Locale.getDefault()).format(new Date())+" • W "+fmt(s[0])+"/"+fmt(s[2])+"/"+fmt(s[1])+" • Temp max "+fmt(t[1])+"°C";String old=p.getString("charge_tests","");String all=out+(old.isEmpty()?"":"\n"+old);String[]a=all.split("\n");StringBuilder b=new StringBuilder();for(int i=0;i<Math.min(10,a.length);i++){if(i>0)b.append("\n");b.append(a[i]);}p.edit().putString("charge_tests",b.toString()).putString("last_charge_test",out).apply();log("Laddningsprov: "+out);toast("Laddningsprov klart");battery89();}}};h.post(watch);}

  void profiles89(){base("🚗 GPS / JOBBLÄGE PRO","Profiler som kan återställas",true);note("Aktiv profil: "+p.getString("profile","Standard"));btn("Balanserad",()->profile("Balanserad",60000,true,true,false));btn("Batteri",()->profile("Batteri",30000,true,false,false));btn("Gaming",()->profile("Gaming",120000,false,true,false));btn("Bil/GPS",()->profile("Bil/GPS",600000,true,true,true));btn("DeX",()->profile("DeX",600000,true,true,false));sec("GPS-snabbval");btn("Platsinställningar",()->open(Settings.ACTION_LOCATION_SOURCE_SETTINGS));btn("Batteriinställningar",()->open(Settings.ACTION_BATTERY_SAVER_SETTINGS));btn("Återställ tidigare läge",()->restoreProfile());}

  void selfTest(){base("🧪 TOOLBOX SELF TEST","Kontrollerar de viktigaste funktionerna",true);testLine("Signering",signatureOk(),signatureFingerprint());testLine("Shizuku installerad",shInstalled(),shInstalled()?"Installerad":"Saknas");testLine("Shizuku tjänst",shAlive(),shAlive()?"Kör":"Ej igång");testLine("Shizuku behörighet",shOk(),shStatus());testLine("Ändra systeminställningar",Settings.System.canWrite(this),Settings.System.canWrite(this)?"Tillåtet":"Behöver tillåtelse");testLine("Batterisensor",temp()>0&&volt()>0,"Temp "+fmt(temp())+"°C • "+volt()+" mV");int apps=getPackageManager().getInstalledApplications(0).size();testLine("Paketvisning",apps>20,apps+" appar synliga");testLine("Lagring",free()>5,free()+" GB ledigt");sec("Resultat");note(signatureOk()&&temp()>0?"✅ Grundfunktionerna ser bra ut.":"⚠️ En eller flera kontroller behöver granskas.");}
  void testLine(String a,boolean ok,String b){TextView t=text((ok?"✅ ":"⚠️ ")+a,18,true);t.setTextColor(ok?GREEN:AMBER);root.addView(t);note(b);}
  String signatureFingerprint(){try{PackageInfo pi;if(Build.VERSION.SDK_INT>=28){pi=getPackageManager().getPackageInfo(getPackageName(),PackageManager.GET_SIGNING_CERTIFICATES);return sha256(pi.signingInfo.getApkContentsSigners()[0].toByteArray());}pi=getPackageManager().getPackageInfo(getPackageName(),PackageManager.GET_SIGNATURES);return sha256(pi.signatures[0].toByteArray());}catch(Exception e){return"Okänd";}}
  boolean signatureOk(){return EXPECTED_CERT.equalsIgnoreCase(signatureFingerprint());}String sha256(byte[]b)throws Exception{byte[]d=MessageDigest.getInstance("SHA-256").digest(b);StringBuilder s=new StringBuilder();for(int i=0;i<d.length;i++){if(i>0)s.append(':');s.append(String.format(Locale.ROOT,"%02X",d[i]));}return s.toString();}

  void backupPage(){base("💾 BACKUP / RESTORE","Import ändrar inte paket automatiskt",true);note("Exporten sparar profilnamn, spårade Debloat-paket, laddtester och historik. Import återställer bara Toolbox-data – den kör inga Shizuku-kommandon.");btn("Exportera backup",()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("text/plain");i.putExtra(Intent.EXTRA_TITLE,"S23-Ultra-Toolbox-8.9-Backup.txt");startActivityForResult(i,BACKUP_OUT);});btn("Importera backup",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("text/plain");startActivityForResult(i,BACKUP_IN);});btn("Kopiera diagnostik",()->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("diag",report89()));toast("Kopierat");});sec("Diagnostik");note(report89());}
  String backupText(){String dis=join(p.getStringSet("disabled",new HashSet<>()));String hist=android.util.Base64.encodeToString(p.getString("history","").getBytes(java.nio.charset.StandardCharsets.UTF_8),android.util.Base64.NO_WRAP);String tests=android.util.Base64.encodeToString(p.getString("charge_tests","").getBytes(java.nio.charset.StandardCharsets.UTF_8),android.util.Base64.NO_WRAP);return"S23TOOLBOX_BACKUP=1\nVERSION=8.9\nPROFILE="+p.getString("profile","Standard")+"\nDISABLED="+dis+"\nHISTORY64="+hist+"\nTESTS64="+tests+"\n";}
  String join(Set<String>s){StringBuilder b=new StringBuilder();for(String x:s){if(b.length()>0)b.append(',');b.append(x);}return b.toString();}String decode64(String s){try{return new String(android.util.Base64.decode(s==null?"":s,android.util.Base64.DEFAULT),java.nio.charset.StandardCharsets.UTF_8);}catch(Exception e){return"";}}
  void importBackup(String x){try{if(!x.contains("S23TOOLBOX_BACKUP=1")){toast("Inte en Toolbox-backup");return;}HashMap<String,String>m=new HashMap<>();for(String l:x.split("\n")){int i=l.indexOf('=');if(i>0)m.put(l.substring(0,i),l.substring(i+1));}Set<String>d=new HashSet<>();String ds=m.get("DISABLED");if(ds!=null&&!ds.isEmpty())d.addAll(Arrays.asList(ds.split(",")));p.edit().putString("profile",m.containsKey("PROFILE")?m.get("PROFILE"):"Standard").putStringSet("disabled",d).putString("history",decode64(m.get("HISTORY64"))).putString("charge_tests",decode64(m.get("TESTS64"))).apply();log("Backup importerad");toast("Backup importerad");show();}catch(Exception e){toast("Backup kunde inte importeras");}}
  String report89(){return"S23 Ultra Toolbox 8.9\n"+Build.MANUFACTURER+" "+Build.MODEL+"\nAndroid "+Build.VERSION.RELEASE+" SDK "+Build.VERSION.SDK_INT+"\nBuild "+Build.DISPLAY+"\nBatteri "+level()+"% • "+batteryHealthName()+"\nTemperatur "+fmt(temp())+"°C\nSpänning "+String.format(Locale.ROOT,"%.3f",volt()/1000.0)+" V\nRAM "+ram()+"%\nLedigt "+free()+" GB\n"+shStatus()+"\nSignering "+(signatureOk()?"Verifierad":"Avvikande")+"\nProfil "+p.getString("profile","Standard")+"\nToolbox-avaktiverade "+p.getStringSet("disabled",new HashSet<>()).size()+"\nSenaste ändring: "+p.getString("last_change","Ingen")+"\nSenaste laddningsprov: "+p.getString("last_charge_test","Ingen")+"\nHealth "+score()+"/100";}
  @Override protected void onActivityResult(int q,int z,Intent d){if((q==BACKUP_OUT||q==BACKUP_IN)){if(z!=RESULT_OK||d==null||d.getData()==null)return;if(q==BACKUP_OUT)try(OutputStream o=getContentResolver().openOutputStream(d.getData())){o.write(backupText().getBytes(java.nio.charset.StandardCharsets.UTF_8));toast("Backup sparad");}catch(Exception e){toast("Kunde inte spara");}else try(InputStream in=getContentResolver().openInputStream(d.getData())){ByteArrayOutputStream b=new ByteArrayOutputStream();byte[]buf=new byte[4096];int n;while((n=in.read(buf))>0)b.write(buf,0,n);importBackup(b.toString("UTF-8"));}catch(Exception e){toast("Kunde inte läsa backup");}return;}super.onActivityResult(q,z,d);}

  void quickCenter(){base("⚙️ QUICK CENTER","Snabbvägar till vanliga systeminställningar",true);btn("Skärm",()->open(Settings.ACTION_DISPLAY_SETTINGS));btn("Batteri",()->open(Settings.ACTION_BATTERY_SAVER_SETTINGS));btn("Lagring",()->open(Settings.ACTION_INTERNAL_STORAGE_SETTINGS));btn("Plats",()->open(Settings.ACTION_LOCATION_SOURCE_SETTINGS));btn("Ljud",()->open(Settings.ACTION_SOUND_SETTINGS));btn("Appar",()->open(Settings.ACTION_APPLICATION_SETTINGS));btn("Specialåtkomst: ändra systeminställningar",()->startActivity(new Intent(Settings.ACTION_MANAGE_WRITE_SETTINGS,Uri.parse("package:"+getPackageName()))));btn("Toolbox appinfo",()->startActivity(new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName()))));}

  void camera89(){base("📸 CAMERA GUIDE 5.2","S23 Ultra scenprofiler",true);cam("Vardag","12 MP • 1x/3x • Auto HDR.");cam("Barn/djur","12 MP • bra ljus • 1x/3x • undvik nattläge vid rörelse.");cam("Mörkt rum","12 MP • 1x • nattläge • håll stilla.");cam("Måne","10x • stabilt stöd • sänk exponeringen.");cam("Konsert","3x/10x • sänk exponeringen • 4K30 i svagt ljus.");cam("Landskap","12 MP normalt. 200 MP bara i bra ljus och stilla motiv.");cam("Porträtt","3x ger ofta naturligare perspektiv.");cam("Video","4K60 i bra ljus/rörelse, 4K30 i svagare ljus.");cam("Expert RAW","Bra när du vill efterbehandla. Använd RAW när du verkligen behöver extra redigeringsmån.");btn("Starta kameran",()->{try{startActivity(new Intent("android.media.action.STILL_IMAGE_CAMERA"));}catch(Exception e){}});}
}
