package se.smartoptimizer.toolbox;

import android.app.*;
import android.os.*;
import android.content.*;
import android.content.pm.*;
import android.graphics.Color;
import android.media.AudioManager;
import android.net.Uri;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.lang.reflect.Method;
import java.text.SimpleDateFormat;
import java.util.*;
import rikka.shizuku.Shizuku;

public class MainActivity extends Activity {
  LinearLayout root; boolean onHome=true; final int SHIZUKU_REQ=4201; SharedPreferences prefs; Handler handler=new Handler(Looper.getMainLooper()); Runnable thermalTask; int thermalSamples=0;
  interface Go{void run();}

  final String[][] PACKAGES={
    {"Samsung Free","com.samsung.android.app.spage","Säker","Samsung"},{"Samsung Global Goals","com.samsung.sree","Säker","Samsung"},{"AR Zone","com.samsung.android.arzone","Säker","Samsung"},{"Samsung Kids","com.samsung.android.kidsinstaller","Säker","Samsung"},{"Samsung Members","com.samsung.android.voc","Valfritt","Samsung"},{"Samsung Shop","com.samsung.ecomm.global","Valfritt","Samsung"},{"Bixby Voice","com.samsung.android.bixby.agent","Försiktig","Samsung"},{"Bixby Vision","com.samsung.android.visionintelligence","Valfritt","Samsung"},{"SmartThings","com.samsung.android.oneconnect","Försiktig","Samsung"},{"Samsung Health","com.sec.android.app.shealth","Valfritt","Samsung"},{"Samsung Internet","com.sec.android.app.sbrowser","Valfritt","Samsung"},{"Samsung Wallet","com.samsung.android.spay","Försiktig","Samsung"},{"Samsung Notes","com.samsung.android.app.notes","Valfritt","Samsung"},{"Samsung Email","com.samsung.android.email.provider","Valfritt","Samsung"},{"Samsung Pass","com.samsung.android.samsungpass","Försiktig","Samsung"},{"Samsung Cloud","com.samsung.android.scloud","Försiktig","Samsung"},{"Game Launcher","com.samsung.android.game.gamehome","Valfritt","Samsung"},{"Google TV","com.google.android.videos","Säker","Google"},{"Google Meet","com.google.android.apps.tachyon","Valfritt","Google"},{"YouTube Music","com.google.android.apps.youtube.music","Valfritt","Google"},{"Google One","com.google.android.apps.subscriptions.red","Valfritt","Google"},{"Android Auto","com.google.android.projection.gearhead","Försiktig","Google"},{"Google Drive","com.google.android.apps.docs","Valfritt","Google"},{"Microsoft OneDrive","com.microsoft.skydrive","Valfritt","Microsoft"},{"LinkedIn","com.linkedin.android","Säker","Microsoft"},{"Meta App Manager","com.facebook.appmanager","Valfritt","Meta"},{"Meta Services","com.facebook.services","Valfritt","Meta"},{"Meta App Installer","com.facebook.system","Valfritt","Meta"}
  };

  final Shizuku.OnRequestPermissionResultListener permListener=(requestCode,grantResult)->{if(requestCode==SHIZUKU_REQ){toast(grantResult==PackageManager.PERMISSION_GRANTED?"Shizuku-behörighet beviljad":"Shizuku-behörighet nekad");showHome();}};
  @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("toolbox",MODE_PRIVATE);try{Shizuku.addRequestPermissionResultListener(permListener);}catch(Throwable ignored){}showHome();}
  @Override protected void onDestroy(){if(thermalTask!=null)handler.removeCallbacks(thermalTask);try{Shizuku.removeRequestPermissionResultListener(permListener);}catch(Throwable ignored){}super.onDestroy();}
  @Override public void onBackPressed(){if(!onHome)showHome();else super.onBackPressed();}

  TextView text(String s,int z,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(Color.WHITE);v.setTypeface(null,bold?1:0);return v;}
  void section(String s){TextView v=text(s,19,true);v.setTextColor(Color.rgb(120,255,150));v.setPadding(0,20,0,7);root.addView(v);}
  void note(String s){TextView v=text(s,14,false);v.setTextColor(Color.LTGRAY);v.setPadding(8,6,8,6);root.addView(v);}
  Button button(String s,Go g){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setOnClickListener(v->g.run());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,7,0,0);root.addView(b,lp);return b;}
  void base(String title,String subtitle,boolean back){onHome=!back;if(thermalTask!=null){handler.removeCallbacks(thermalTask);thermalTask=null;}getWindow().setStatusBarColor(Color.rgb(14,18,24));getWindow().setNavigationBarColor(Color.rgb(14,18,24));ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.rgb(14,18,24));root.setPadding(26,26+statusBarHeight(),26,50);if(Build.VERSION.SDK_INT>=30)sv.setOnApplyWindowInsetsListener((v,insets)->{android.graphics.Insets bars=insets.getInsets(WindowInsets.Type.systemBars());root.setPadding(26,26+bars.top,26,50+bars.bottom);return insets;});if(back){Button b=new Button(this);b.setText("← Tillbaka");b.setAllCaps(false);b.setOnClickListener(v->showHome());root.addView(b);}TextView h=text(title,26,true);h.setPadding(0,back?12:0,0,0);root.addView(h);TextView st=text(subtitle,14,false);st.setTextColor(Color.rgb(120,255,150));st.setPadding(0,4,0,16);root.addView(st);sv.addView(root);setContentView(sv);}
  int statusBarHeight(){int id=getResources().getIdentifier("status_bar_height","dimen","android");return id>0?getResources().getDimensionPixelSize(id):0;}
  void addCard(String a,String b,Go g){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(18,14,18,14);c.setBackgroundColor(Color.rgb(24,30,40));TextView h=text(a,18,true);c.addView(h);TextView d=text(b,13,false);d.setTextColor(Color.LTGRAY);d.setPadding(0,4,0,3);c.addView(d);c.setOnClickListener(v->g.run());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,10,0,0);root.addView(c,lp);}

  void showHome(){base("S23 ULTRA TOOLBOX 8.4","Samsung S23 Ultra • Shizuku • analys • profiler",false);dashboard();addCard("🔎 Analysera min telefon","Djup analys med optimeringspoäng och konkreta rekommendationer.",()->analysisPage());addCard("⚡ Smart Optimize 4.1","Förhandsgranska och aktivera säkra profiler.",()->optimizePage());addCard("🛡️ Smart Debloat 3.0","Samsung/Google/Meta/Microsoft • filter • status • återställning.",()->debloatPage("","Alla"));addCard("🎛️ Profile Editor","Skapa och spara din egen profil.",()->profileEditor());addCard("📦 App Inspector","Kontrollera paket-ID, version och systemstatus för en app.",()->appInspector());addCard("🌡️ Thermal Watch","Följ temperaturen över 60 sekunder och spara historik.",()->thermalPage());addCard("🚀 Performance Center","Balanserad, Max respons, Gaming, Batteri och DeX.",()->performancePage());addCard("🔋 Battery Health","Laddning, temperatur, spänning och batteridata.",()->batteryPage());addCard("🎮 Gaming Dashboard","Temperatur, RAM, batteri, volym och spelprofil.",()->gamingPage());addCard("🖥️ DeX Center","Arbetsprofil och praktiska DeX-snabbval.",()->dexPage());addCard("📸 Camera Guide Pro","Vardag, natt, barn/djur, zoom, måne, porträtt och video.",()->cameraPage());addCard("🔊 Audio Center","Volymreglage direkt i appen.",()->audioPage());addCard("🔧 Shizuku Tools",shizukuStatus(),()->shizukuPage());addCard("↩️ Backup & Restore","Spara profil, skydd och Debloat-lista.",()->restorePage());addCard("🔄 Efter systemuppdatering","Se om tidigare Debloat-val återaktiverats.",()->updateCheckPage());addCard("📖 Tips & Tricks 3.0","Sökbar guide för S23 Ultra.",()->tipsPage(""));addCard("🕘 Historik & skydd","Senaste Toolbox-åtgärderna.",()->historyPage());}
  void dashboard(){Intent i=batteryIntent();int lvl=i==null?-1:i.getIntExtra(BatteryManager.EXTRA_LEVEL,-1);float t=i==null?0:i.getIntExtra(BatteryManager.EXTRA_TEMPERATURE,0)/10f;int suggestions=0;for(String[]p:PACKAGES)if(isInstalled(p[1])&&isPackageEnabled(p[1])&&!isProtected(p[1])&&!p[2].equals("Försiktig"))suggestions++;String top="Profil: "+prefs.getString("profile","Ingen")+"   •   Shizuku: "+(hasShizukuPermission()?"✓":"–")+"\nTemp: "+tempLabel(t)+" "+t+"°C   •   RAM: "+ramPercent()+"%   •   Debloat: "+suggestions+" förslag";TextView v=text(top,14,true);v.setPadding(16,14,16,14);v.setBackgroundColor(Color.rgb(25,32,42));root.addView(v);note("🔋 "+lvl+"% • 💾 "+freeGb()+" GB ledigt • "+Build.MODEL+" • Android "+Build.VERSION.RELEASE);}

  Intent batteryIntent(){return registerReceiver(null,new IntentFilter(Intent.ACTION_BATTERY_CHANGED));}
  int ramPercent(){ActivityManager am=(ActivityManager)getSystemService(ACTIVITY_SERVICE);ActivityManager.MemoryInfo mi=new ActivityManager.MemoryInfo();am.getMemoryInfo(mi);return mi.totalMem>0?(int)((mi.totalMem-mi.availMem)*100/mi.totalMem):0;}
  long freeGb(){StatFs fs=new StatFs(getFilesDir().getPath());return fs.getAvailableBytes()/1073741824L;}
  float temp(){Intent i=batteryIntent();return i==null?0:i.getIntExtra(BatteryManager.EXTRA_TEMPERATURE,0)/10f;}
  String tempLabel(float t){return t>=43?"Mycket varm":t>=40?"Varm":t>=35?"Normal/varm":"Normal";}

  void analysisPage(){base("🔎 TELEFONANALYS","Mätvärden + förklaringar + rekommendationer",true);Intent i=batteryIntent();int level=i==null?-1:i.getIntExtra(BatteryManager.EXTRA_LEVEL,-1),ram=ramPercent(),timeout=60000;float t=temp();try{timeout=Settings.System.getInt(getContentResolver(),Settings.System.SCREEN_OFF_TIMEOUT);}catch(Exception ignored){}int installed=0,enabled=0;for(String[]p:PACKAGES)if(isInstalled(p[1])){installed++;if(isPackageEnabled(p[1]))enabled++;}int score=100;if(t>=43)score-=18;else if(t>=40)score-=8;if(ram>=88)score-=10;else if(ram>=80)score-=5;if(timeout>120000)score-=7;if(!hasShizukuPermission())score-=5;if(level<15)score-=3;if(freeGb()<20)score-=8;score=Math.max(0,score);section("Optimeringspoäng: "+score+" / 100");note("Batteri "+level+"% • "+t+"°C • RAM "+ram+"% • "+freeGb()+" GB ledigt • timeout "+(timeout/1000)+" s");section("Rekommendationer");note(t>=43?"🔥 Temperaturen är hög. Minska tung belastning tills den sjunker.":"✅ Temperaturen är inom rimligt område.");note(ram>=88?"🧠 RAM-belastningen är hög, men Android bör få hantera minnet själv.":"✅ RAM-belastningen ser normal ut.");note(timeout>120000?"⏱️ Sänk skärmtimeout till 30–60 sek för bättre batteritid.":"✅ Skärmtimeouten är rimlig.");note(freeGb()<20?"💾 Lagringen börjar bli låg. Frigör utrymme för bättre marginal.":"✅ Gott om ledigt lagringsutrymme.");note("🛡️ "+installed+" kända valfria paket hittade, "+enabled+" är aktiva.");button("Förhandsgranska balanserad profil",()->confirmProfile("Balanserad",60000,true,true));button("Öppna Debloat 3.0",()->debloatPage("","Alla"));log("Analys körd • poäng "+score);}

  void optimizePage(){base("⚡ SMART OPTIMIZE 4.1","Inga falska RAM-rensningar eller CPU-tweaks",true);button("⚖️ Balanserad",()->confirmProfile("Balanserad",60000,true,true));button("🚀 Max respons",()->confirmProfile("Max respons",120000,false,true));button("🔋 Batteri",()->confirmProfile("Batteri",30000,true,false));button("🎮 Gaming",()->confirmProfile("Gaming",120000,false,true));button("🖥️ DeX",()->confirmProfile("DeX",120000,true,true));String custom=prefs.getString("custom_name","");if(!custom.isEmpty())button("🎛️ Min profil: "+custom,()->applySavedCustom());}
  void confirmProfile(String name,int timeout,boolean adaptive,boolean rotate){String msg="Profil: "+name+"\n\n• Timeout: "+(timeout/1000)+" sek\n• Adaptiv ljusstyrka: "+(adaptive?"På":"Av")+"\n• Auto-rotera: "+(rotate?"På":"Av")+"\n\nToolbox ändrar inte CPU/GPU-klockor.";new AlertDialog.Builder(this).setTitle("Tillämpa profil?").setMessage(msg).setNegativeButton("Avbryt",null).setPositiveButton("Tillämpa",(d,w)->applyProfile(name,timeout,adaptive,rotate)).show();}
  void applyProfile(String name,int timeout,boolean adaptive,boolean rotate){if(!ensureWrite())return;try{Settings.System.putInt(getContentResolver(),Settings.System.SCREEN_OFF_TIMEOUT,timeout);Settings.System.putInt(getContentResolver(),Settings.System.SCREEN_BRIGHTNESS_MODE,adaptive?1:0);Settings.System.putInt(getContentResolver(),Settings.System.ACCELEROMETER_ROTATION,rotate?1:0);prefs.edit().putString("profile",name).apply();toast(name+" aktiverad");log("Profil aktiverad: "+name);}catch(Exception e){toast("Profilen kunde inte tillämpas fullt ut");}}

  void profileEditor(){base("🎛️ PROFILE EDITOR","Skapa din egen återanvändbara profil",true);EditText name=new EditText(this);name.setHint("Namn, t.ex. Bil");name.setText(prefs.getString("custom_name","Min profil"));name.setTextColor(Color.WHITE);name.setHintTextColor(Color.GRAY);root.addView(name);EditText sec=new EditText(this);sec.setHint("Skärmtimeout i sekunder (15–600)");sec.setInputType(2);sec.setText(String.valueOf(prefs.getInt("custom_timeout",60)));sec.setTextColor(Color.WHITE);sec.setHintTextColor(Color.GRAY);root.addView(sec);CheckBox adaptive=new CheckBox(this);adaptive.setText("Adaptiv ljusstyrka");adaptive.setTextColor(Color.WHITE);adaptive.setChecked(prefs.getBoolean("custom_adaptive",true));root.addView(adaptive);CheckBox rotate=new CheckBox(this);rotate.setText("Auto-rotera");rotate.setTextColor(Color.WHITE);rotate.setChecked(prefs.getBoolean("custom_rotate",true));root.addView(rotate);button("Spara profil",()->{try{int s=Math.max(15,Math.min(600,Integer.parseInt(sec.getText().toString())));String n=name.getText().toString().trim();if(n.isEmpty())n="Min profil";prefs.edit().putString("custom_name",n).putInt("custom_timeout",s).putBoolean("custom_adaptive",adaptive.isChecked()).putBoolean("custom_rotate",rotate.isChecked()).apply();toast("Profil sparad");log("Egen profil sparad: "+n);}catch(Exception e){toast("Kontrollera timeout-värdet");}});button("Aktivera sparad profil",()->applySavedCustom());}
  void applySavedCustom(){String n=prefs.getString("custom_name","");if(n.isEmpty()){toast("Skapa en profil först");return;}confirmProfile(n,prefs.getInt("custom_timeout",60)*1000,prefs.getBoolean("custom_adaptive",true),prefs.getBoolean("custom_rotate",true));}

  void performancePage(){base("🚀 PERFORMANCE CENTER","Verkliga inställningar som Android tillåter",true);button("⚖️ Balanserad",()->confirmProfile("Balanserad",60000,true,true));button("🚀 Max respons",()->confirmProfile("Max respons",120000,false,true));button("🎮 Gaming",()->confirmProfile("Gaming",120000,false,true));button("🔋 Batteri",()->confirmProfile("Batteri",30000,true,false));button("🖥️ DeX",()->confirmProfile("DeX",120000,true,true));section("Direktreglage");writeSwitch("Auto-rotera",Settings.System.ACCELEROMETER_ROTATION,1,0);writeSwitch("Adaptiv ljusstyrka",Settings.System.SCREEN_BRIGHTNESS_MODE,1,0);button("Samsungs skärmmeny för QHD+/120 Hz",()->open(Settings.ACTION_DISPLAY_SETTINGS));}

  void debloatPage(String query,String filter){base("🛡️ SMART DEBLOAT 3.0","Filter • sök • risknivå • status • återställning",true);if(!hasShizukuPermission()){note("⚠️ Shizuku måste vara igång och behörig.");button("Ge Shizuku-behörighet",()->requestShizuku());}else note("✅ Shizuku är aktiv och behörig.");Spinner sp=new Spinner(this);String[]groups={"Alla","Samsung","Google","Meta","Microsoft","Säker","Valfritt","Försiktig"};ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,groups);sp.setAdapter(a);int pos=Arrays.asList(groups).indexOf(filter);sp.setSelection(Math.max(0,pos));root.addView(sp);EditText search=new EditText(this);search.setHint("Sök app eller paket…");search.setText(query);search.setTextColor(Color.WHITE);search.setHintTextColor(Color.GRAY);root.addView(search);button("Filtrera / sök",()->debloatPage(search.getText().toString().trim(),String.valueOf(sp.getSelectedItem())));section("Installerade matchningar");String q=query.toLowerCase(Locale.ROOT);int shown=0;for(String[]p:PACKAGES){if(!isInstalled(p[1]))continue;String f=filter;if(!f.equals("Alla")&&!p[2].equals(f)&&!p[3].equals(f))continue;if(!q.isEmpty()&&!(p[0]+" "+p[1]+" "+p[2]+" "+p[3]).toLowerCase(Locale.ROOT).contains(q))continue;packageControl(p);shown++;}if(shown==0)note("Inga matchande installerade paket hittades.");section("Återställning");button("Återställ allt Toolbox har avaktiverat",()->confirmRestoreAll());}
  void packageControl(String[]p){String name=p[0],pkg=p[1],risk=p[2],group=p[3];boolean enabled=isPackageEnabled(pkg);section((isProtected(pkg)?"🔒 ":"")+name+" • "+risk);note(group+" • "+pkg+"\nStatus: "+(enabled?"✅ Aktiv":"⛔ Avaktiverad"));LinearLayout row=new LinearLayout(this);Button d=new Button(this);d.setText("Avaktivera");d.setAllCaps(false);d.setEnabled(enabled&&!isProtected(pkg));d.setOnClickListener(v->confirmDisable(name,pkg));row.addView(d,new LinearLayout.LayoutParams(0,-2,1));Button e=new Button(this);e.setText("Återställ");e.setAllCaps(false);e.setEnabled(!enabled);e.setOnClickListener(v->runPmTracked("pm enable --user 0 "+pkg,"Återställde "+name,pkg,false));row.addView(e,new LinearLayout.LayoutParams(0,-2,1));root.addView(row);button(isProtected(pkg)?"Ta bort skydd":"Skydda paket",()->{setProtected(pkg,!isProtected(pkg));debloatPage("","Alla");});}
  void confirmDisable(String name,String pkg){new AlertDialog.Builder(this).setTitle("Avaktivera "+name+"?").setMessage("Paket: "+pkg+"\n\nÅtgärden kan återställas. Paket markerade Försiktig bör bara avaktiveras om du vet att du inte använder funktionen.").setNegativeButton("Avbryt",null).setPositiveButton("Avaktivera",(d,w)->runPmTracked("pm disable-user --user 0 "+pkg,"Avaktiverade "+name,pkg,true)).show();}
  void runPmTracked(String command,String success,String pkg,boolean disabled){if(!hasShizukuPermission()){requestShizuku();return;}new Thread(()->{try{Method m=Shizuku.class.getDeclaredMethod("newProcess",String[].class,String[].class,String.class);m.setAccessible(true);java.lang.Process p=(java.lang.Process)m.invoke(null,new Object[]{new String[]{"sh","-c",command},null,null});int code=p.waitFor();runOnUiThread(()->{if(code==0){setDisabledTracked(pkg,disabled);toast(success);log(success);}else toast("Åtgärden misslyckades (kod "+code+")");});}catch(Throwable e){runOnUiThread(()->toast("Shizuku-kommandot kunde inte köras"));}}).start();}
  void setDisabledTracked(String pkg,boolean disabled){Set<String>s=new HashSet<>(prefs.getStringSet("disabled",new HashSet<>()));if(disabled)s.add(pkg);else s.remove(pkg);prefs.edit().putStringSet("disabled",s).apply();}
  void confirmRestoreAll(){new AlertDialog.Builder(this).setTitle("Återställ alla?").setMessage("Alla paket som Toolbox har avaktiverat återaktiveras.").setNegativeButton("Avbryt",null).setPositiveButton("Återställ",(d,w)->restoreAll()).show();}
  void restoreAll(){Set<String>s=new HashSet<>(prefs.getStringSet("disabled",new HashSet<>()));if(s.isEmpty()){toast("Inget att återställa");return;}for(String pkg:s)runPmTracked("pm enable --user 0 "+pkg,"Återställde "+pkg,pkg,false);}

  void appInspector(){base("📦 APP INSPECTOR","Kontrollera en app utan att ändra något",true);EditText e=new EditText(this);e.setHint("Paket-ID, t.ex. com.samsung.android.app.spage");e.setTextColor(Color.WHITE);e.setHintTextColor(Color.GRAY);root.addView(e);button("Inspektera paket",()->inspect(e.getText().toString().trim()));section("Snabbval");for(String[]p:PACKAGES)if(isInstalled(p[1]))button(p[0]+" • "+p[3],()->inspect(p[1]));}
  void inspect(String pkg){if(pkg.isEmpty()){toast("Ange paket-ID");return;}try{PackageManager pm=getPackageManager();ApplicationInfo ai=pm.getApplicationInfo(pkg,0);PackageInfo pi=pm.getPackageInfo(pkg,0);String label=String.valueOf(pm.getApplicationLabel(ai));boolean system=(ai.flags&ApplicationInfo.FLAG_SYSTEM)!=0;new AlertDialog.Builder(this).setTitle(label).setMessage("Paket: "+pkg+"\nVersion: "+pi.versionName+"\nVersion code: "+pi.getLongVersionCode()+"\nTyp: "+(system?"Systemapp":"Användarapp")+"\nStatus: "+(ai.enabled?"Aktiv":"Avaktiverad")+"\n\nToolbox ändrar inget från App Inspector.").setPositiveButton("OK",null).show();}catch(Exception ex){toast("Paketet hittades inte");}}

  void thermalPage(){base("🌡️ THERMAL WATCH","12 mätningar under 60 sekunder",true);section("Aktuellt");note("Temperatur: "+temp()+"°C • "+tempLabel(temp()));section("Historik");note(prefs.getString("temp_history","Ingen historik ännu."));button("Starta 60 sek Thermal Watch",()->startThermalWatch());button("Rensa historik",()->{prefs.edit().remove("temp_history").apply();thermalPage();});}
  void startThermalWatch(){thermalSamples=0;toast("Thermal Watch startad");thermalTask=new Runnable(){public void run(){float t=temp();saveTempSample(t);thermalSamples++;if(thermalSamples<12)handler.postDelayed(this,5000);else{toast("Thermal Watch klar");thermalTask=null;thermalPage();}}};handler.post(thermalTask);}
  void saveTempSample(float t){String now=new SimpleDateFormat("MM-dd HH:mm:ss",Locale.getDefault()).format(new Date());String old=prefs.getString("temp_history","");String n=now+" • "+t+"°C • "+tempLabel(t)+(old.isEmpty()?"":"\n"+old);String[]lines=n.split("\n");StringBuilder out=new StringBuilder();for(int i=0;i<Math.min(24,lines.length);i++)out.append(lines[i]).append(i<Math.min(24,lines.length)-1?"\n":"");prefs.edit().putString("temp_history",out.toString()).apply();}

  void batteryPage(){base("🔋 BATTERY HEALTH","Laddning, temperatur och elektriska värden",true);Intent i=batteryIntent();int lvl=i==null?-1:i.getIntExtra(BatteryManager.EXTRA_LEVEL,-1),mv=i==null?0:i.getIntExtra(BatteryManager.EXTRA_VOLTAGE,0),plug=i==null?0:i.getIntExtra(BatteryManager.EXTRA_PLUGGED,0),health=i==null?0:i.getIntExtra(BatteryManager.EXTRA_HEALTH,0);float t=temp();section("Live");note("Batteri: "+lvl+"%\nTemperatur: "+t+"°C ("+tempLabel(t)+")\nSpänning: "+(mv/1000f)+" V\nLaddning: "+(plug==0?"Inte ansluten":"Ansluten")+"\nAndroid health-kod: "+health);button("Aktivera batteriprofil",()->confirmProfile("Batteri",30000,true,false));button("Öppna batterisparläge",()->open(Settings.ACTION_BATTERY_SAVER_SETTINGS));note("Android ger inte vanliga appar en tillförlitlig kapacitetsprocent för batterihälsa. Toolbox visar därför inte en påhittad hälsoprocent.");}
  void gamingPage(){base("🎮 GAMING DASHBOARD","Livevärden före spel",true);Intent i=batteryIntent();int lvl=i==null?-1:i.getIntExtra(BatteryManager.EXTRA_LEVEL,-1);section("Status");note("🔋 "+lvl+"% • 🌡️ "+temp()+"°C ("+tempLabel(temp())+") • 🧠 RAM "+ramPercent()+"%\nAktiv profil: "+prefs.getString("profile","Ingen"));button("Aktivera Gaming-profil",()->confirmProfile("Gaming",120000,false,true));addVolume("Spel / media",AudioManager.STREAM_MUSIC);button("Öppna Samsung Game Booster",()->game());button("Uppdatera",()->gamingPage());}
  void dexPage(){base("🖥️ DEX CENTER","S23 Ultra som arbetsdator",true);note("DeX-profil: 2 min timeout, adaptiv ljusstyrka och rotation. Samsung styr vissa DeX-val i sina egna menyer.");button("Aktivera DeX-profil",()->confirmProfile("DeX",120000,true,true));button("Skärminställningar",()->open(Settings.ACTION_DISPLAY_SETTINGS));button("Ljudinställningar",()->open(Settings.ACTION_SOUND_SETTINGS));}
  void cameraPage(){base("📸 CAMERA GUIDE PRO","Scenbaserade rekommendationer",true);cameraProfile("Vardag","12 MP • Auto HDR • 1x/3x. Bäst balans mellan hastighet och kvalitet.");cameraProfile("Natt","12 MP eller nattläge. Håll still och undvik 200 MP i svagt ljus.");cameraProfile("Barn / djur","12 MP och bra ljus. Prioritera kort slutartid om motivet rör sig.");cameraProfile("Landskap","200 MP i starkt ljus på stilla motiv; annars 12 MP för bättre HDR.");cameraProfile("10× zoom","Använd 10x i bra ljus och stabilisera telefonen.");cameraProfile("Måne","10x + stöd. Sänk exponeringen för att behålla detaljer.");cameraProfile("Porträtt","3x ger ofta naturligare perspektiv än 1x.");cameraProfile("Video","4K60 för rörelse, 4K30 i svagare ljus, 8K när detalj väger tyngre än filstorlek.");button("Starta kameran",()->camera());}
  void cameraProfile(String name,String tip){section(name);note(tip);}
  void audioPage(){base("🔊 AUDIO CENTER","Volym direkt i Toolbox",true);addVolume("Media",AudioManager.STREAM_MUSIC);addVolume("Ringsignal",AudioManager.STREAM_RING);addVolume("Notiser",AudioManager.STREAM_NOTIFICATION);addVolume("Alarm",AudioManager.STREAM_ALARM);button("Dolby Atmos / ljudinställningar",()->open(Settings.ACTION_SOUND_SETTINGS));}
  void addVolume(String label,int stream){AudioManager am=(AudioManager)getSystemService(AUDIO_SERVICE);section(label);SeekBar s=new SeekBar(this);s.setMax(am.getStreamMaxVolume(stream));s.setProgress(am.getStreamVolume(stream));s.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int p,boolean f){if(f)am.setStreamVolume(stream,p,0);}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});root.addView(s);}

  void shizukuPage(){base("🔧 SHIZUKU TOOLS","API-status och behörighet",true);section("Status");note(shizukuStatus());if(shizukuBinderAlive()&&!hasShizukuPermission())button("Begär Shizuku-behörighet",()->requestShizuku());if(shizukuInstalled())button("Öppna Shizuku",()->openPkg("moe.shizuku.privileged.api"));note("Shizuku används främst för Debloat. Android/Samsung kan fortfarande skydda vissa paket.");}
  void restorePage(){base("↩️ BACKUP & RESTORE","Profil • Debloat • skyddade paket",true);Set<String>s=prefs.getStringSet("disabled",new HashSet<>());note("Spårade avaktiverade paket: "+s.size()+"\nAktiv profil: "+prefs.getString("profile","Ingen")+"\nEgen profil: "+prefs.getString("custom_name","Ingen"));button("Återställ alla avaktiverade paket",()->confirmRestoreAll());section("Backupkod");String code=backupCode();note(code);button("Kopiera backupkod",()->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("S23 Toolbox backup",code));toast("Backupkod kopierad");});button("Importera backupkod",()->importBackupDialog());}
  String backupCode(){Set<String>d=prefs.getStringSet("disabled",new HashSet<>());Set<String>p=new HashSet<>();for(String[]x:PACKAGES)if(isProtected(x[1]))p.add(x[1]);return"S23TB84|profile="+prefs.getString("profile","Ingen")+"|custom="+prefs.getString("custom_name","")+","+prefs.getInt("custom_timeout",60)+","+prefs.getBoolean("custom_adaptive",true)+","+prefs.getBoolean("custom_rotate",true)+"|disabled="+join(d)+"|protected="+join(p);}
  String join(Set<String>s){StringBuilder b=new StringBuilder();for(String x:s){if(b.length()>0)b.append(",");b.append(x);}return b.toString();}
  void importBackupDialog(){final EditText e=new EditText(this);e.setHint("Klistra in backupkod");new AlertDialog.Builder(this).setTitle("Importera backup").setView(e).setNegativeButton("Avbryt",null).setPositiveButton("Importera",(d,w)->importBackup(e.getText().toString())).show();}
  void importBackup(String code){if(!code.startsWith("S23TB84|")){toast("Ogiltig backupkod");return;}try{String[]parts=code.split("\\|");SharedPreferences.Editor ed=prefs.edit();for(String part:parts){if(part.startsWith("profile="))ed.putString("profile",part.substring(8));else if(part.startsWith("custom=")){String[]c=part.substring(7).split(",");if(c.length>=4){ed.putString("custom_name",c[0]);ed.putInt("custom_timeout",Integer.parseInt(c[1]));ed.putBoolean("custom_adaptive",Boolean.parseBoolean(c[2]));ed.putBoolean("custom_rotate",Boolean.parseBoolean(c[3]));}}else if(part.startsWith("disabled=")){Set<String>x=new HashSet<>();String v=part.substring(9);if(!v.isEmpty())x.addAll(Arrays.asList(v.split(",")));ed.putStringSet("disabled",x);}else if(part.startsWith("protected=")){for(String[]x:PACKAGES)ed.putBoolean("protect_"+x[1],false);String v=part.substring(10);if(!v.isEmpty())for(String p:v.split(","))ed.putBoolean("protect_"+p,true);}}ed.apply();toast("Backup importerad");log("Backup importerad");}catch(Exception ex){toast("Kunde inte importera backup");}}

  void updateCheckPage(){base("🔄 EFTER SYSTEMUPPDATERING","Kontrollera ändringar efter Samsung/Android-uppdatering",true);String current=Build.FINGERPRINT,previous=prefs.getString("fingerprint","");if(previous.isEmpty())note("Ingen tidigare systemversion sparad.");else if(previous.equals(current))note("✅ Samma system-build som vid senaste kontrollen.");else note("🟡 System-build har ändrats. Granska Debloat och profiler igen.");int changed=0;Set<String>d=prefs.getStringSet("disabled",new HashSet<>());for(String pkg:d)if(isInstalled(pkg)&&isPackageEnabled(pkg))changed++;section("Resultat");note(changed==0?"✅ Inga spårade paket verkar ha återaktiverats.":"⚠️ "+changed+" tidigare avaktiverade paket verkar vara aktiva igen.");button("Öppna Debloat 3.0",()->debloatPage("","Alla"));button("Spara systemversion som kontrollerad",()->{prefs.edit().putString("fingerprint",current).apply();toast("Systemversion sparad");log("Systemuppdateringskontroll sparad");});}

  void tipsPage(String query){base("📖 TIPS & TRICKS 3.0","Sökbar S23 Ultra-guide",true);EditText e=new EditText(this);e.setHint("Sök t.ex. kamera, DeX, S Pen, batteri…");e.setText(query);e.setTextColor(Color.WHITE);e.setHintTextColor(Color.GRAY);root.addView(e);button("Sök",()->tipsPage(e.getText().toString().trim()));tipBlock("Skärm","QHD+ för maximal skärpa. Adaptiv 120 Hz för bäst flyt. Mörkt läge minskar bländning kvällstid.",query);tipBlock("Kamera","12 MP för vardag/mörker. 200 MP i bra ljus. 3x/10x för tele. 4K60 för rörelse. Expert RAW för efterbehandling.",query);tipBlock("Batteri","30–60 sek timeout, adaptiv ljusstyrka och undvik tung belastning när telefonen redan är varm.",query);tipBlock("DeX","Extern skärm + tangentbord/mus. Använd fönsterläge och en längre timeout när du arbetar.",query);tipBlock("S Pen","Screen off memo för snabba anteckningar. Air Command för smart markering, översättning och genvägar.",query);tipBlock("Lagring","Behåll gärna minst 15–20 GB ledigt så systemet har god arbetsmarginal.",query);tipBlock("Säkerhet","Håll systemet uppdaterat och avaktivera bara paket du förstår. Toolbox skyddar inte mot alla felaktiga Debloat-val.",query);}
  void tipBlock(String title,String body,String q){String z=(title+" "+body).toLowerCase(Locale.ROOT);if(q.isEmpty()||z.contains(q.toLowerCase(Locale.ROOT))){section(title);note(body);}}
  void historyPage(){base("🕘 HISTORIK & SKYDD","Senaste 40 Toolbox-åtgärder",true);section("Historik");note(prefs.getString("history","Ingen aktivitet ännu."));section("Skyddade paket");StringBuilder b=new StringBuilder();for(String[]p:PACKAGES)if(isProtected(p[1]))b.append("🔒 ").append(p[0]).append("\n");note(b.length()==0?"Inga paket skyddade.":b.toString());button("Rensa historik",()->{prefs.edit().remove("history").apply();historyPage();});}

  void writeSwitch(String label,String key,int on,int off){Switch sw=new Switch(this);sw.setText(label);sw.setTextColor(Color.WHITE);sw.setTextSize(16);try{sw.setChecked(Settings.System.getInt(getContentResolver(),key,on)==on);}catch(Exception ignored){}sw.setOnCheckedChangeListener((b,c)->{if(!ensureWrite()){b.setChecked(!c);return;}try{Settings.System.putInt(getContentResolver(),key,c?on:off);log(label+" = "+(c?"på":"av"));}catch(Exception e){toast("Kunde inte ändra inställningen");}});root.addView(sw);}
  boolean ensureWrite(){if(Build.VERSION.SDK_INT<23||Settings.System.canWrite(this))return true;toast("Tillåt S23 Ultra Toolbox att ändra systeminställningar");try{startActivity(new Intent(Settings.ACTION_MANAGE_WRITE_SETTINGS,Uri.parse("package:"+getPackageName())));}catch(Exception e){open(Settings.ACTION_SETTINGS);}return false;}
  boolean shizukuInstalled(){try{getPackageManager().getPackageInfo("moe.shizuku.privileged.api",0);return true;}catch(Exception e){return false;}}
  boolean shizukuBinderAlive(){try{return Shizuku.pingBinder();}catch(Throwable e){return false;}}
  boolean hasShizukuPermission(){try{return shizukuBinderAlive()&&Shizuku.checkSelfPermission()==PackageManager.PERMISSION_GRANTED;}catch(Throwable e){return false;}}
  String shizukuStatus(){if(!shizukuInstalled())return"❌ Shizuku är inte installerad";if(!shizukuBinderAlive())return"⚠️ Shizuku installerad men tjänsten är inte igång";return hasShizukuPermission()?"✅ Shizuku aktiv och behörig":"🟡 Shizuku aktiv • behörighet krävs";}
  void requestShizuku(){try{if(!shizukuBinderAlive()){toast("Starta Shizuku först");openPkg("moe.shizuku.privileged.api");return;}if(Shizuku.checkSelfPermission()==PackageManager.PERMISSION_GRANTED){toast("Shizuku är redan behörig");return;}Shizuku.requestPermission(SHIZUKU_REQ);}catch(Throwable e){toast("Kunde inte begära Shizuku-behörighet");}}
  boolean isInstalled(String p){try{getPackageManager().getPackageInfo(p,0);return true;}catch(Exception e){return false;}}
  boolean isPackageEnabled(String p){try{return getPackageManager().getApplicationInfo(p,0).enabled;}catch(Exception e){return false;}}
  boolean isProtected(String p){return prefs.getBoolean("protect_"+p,false);}void setProtected(String p,boolean b){prefs.edit().putBoolean("protect_"+p,b).apply();log((b?"Skyddade ":"Tog bort skydd från ")+p);}
  void log(String s){String old=prefs.getString("history","");String now=new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.getDefault()).format(new Date());String n=now+" • "+s+(old.isEmpty()?"":"\n"+old);String[]lines=n.split("\n");StringBuilder out=new StringBuilder();for(int i=0;i<Math.min(40,lines.length);i++)out.append(lines[i]).append(i<Math.min(40,lines.length)-1?"\n":"");prefs.edit().putString("history",out.toString()).apply();}
  void open(String a){try{startActivity(new Intent(a));}catch(Exception e){startActivity(new Intent(Settings.ACTION_SETTINGS));}}
  boolean openPkg(String p){try{Intent i=getPackageManager().getLaunchIntentForPackage(p);if(i!=null){startActivity(i);return true;}}catch(Exception ignored){}return false;}
  void game(){if(!openPkg("com.samsung.android.game.gamehome"))if(!openPkg("com.samsung.android.game.gametools"))open(Settings.ACTION_SETTINGS);}
  void camera(){try{startActivity(new Intent("android.media.action.STILL_IMAGE_CAMERA"));}catch(Exception e){open(Settings.ACTION_APPLICATION_SETTINGS);}}
  void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
