plugins { id 'com.android.application' }
android {
  namespace 'se.smartoptimizer.toolbox'
  compileSdk 35
  defaultConfig { applicationId 'se.smartoptimizer.toolbox'; minSdk 26; targetSdk 35; versionCode 1110; versionName '10.11' }
  compileOptions { sourceCompatibility JavaVersion.VERSION_11; targetCompatibility JavaVersion.VERSION_11 }
}
dependencies { implementation 'dev.rikka.shizuku:api:13.1.5'; implementation 'dev.rikka.shizuku:provider:13.1.5' }
