package se.minekonomi.app;

import android.app.*;
import android.os.*;
import android.Manifest;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.Typeface;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.text.*;
import java.util.*;

public class MainActivity extends Activity {
    SharedPreferences p;
    LinearLayout root;
    final int BG=Color.rgb(248,250,252), TEXT=Color.rgb(15,23,42), MUTED=Color.rgb(71,85,105), ACC=Color.rgb(15,118,110), RED=Color.rgb(185,28,28), GREEN=Color.rgb(21,128,61), AMBER=Color.rgb(180,83,9);
    final String[] CATS={"Mat","Boende","Transport","Shopping","Räkningar","Resor","Presenter","Hälsa","Övrigt"};

    @Override public void onCreate(Bundle b){ super.onCreate(b); p=getSharedPreferences("min_ekonomi",MODE_PRIVATE); getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE); createChannel(); if(Build.VERSION.SDK_INT>=33 && checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED) requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},7); authenticateThenOpen(); }

    void authenticateThenOpen(){
        if(Build.VERSION.SDK_INT<28){showHome();return;}
        try{
            BiometricPrompt bp=new BiometricPrompt.Builder(this).setTitle("Lås upp Min Ekonomi").setSubtitle("Verifiera dig för att visa din ekonomi").setNegativeButton("Avbryt",getMainExecutor(),(d,w)->finish()).build();
            bp.authenticate(new CancellationSignal(),getMainExecutor(),new BiometricPrompt.AuthenticationCallback(){
                @Override public void onAuthenticationSucceeded(BiometricPrompt.AuthenticationResult r){showHome();}
                @Override public void onAuthenticationError(int e,CharSequence s){ if(e==BiometricPrompt.BIOMETRIC_ERROR_NO_BIOMETRICS || e==BiometricPrompt.BIOMETRIC_ERROR_HW_NOT_PRESENT || e==BiometricPrompt.BIOMETRIC_ERROR_HW_UNAVAILABLE) showHome(); }
            });
        }catch(Exception e){showHome();}
    }

    void createChannel(){ if(Build.VERSION.SDK_INT>=26){ NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE); nm.createNotificationChannel(new NotificationChannel(ReminderReceiver.CHANNEL,"Räkningspåminnelser",NotificationManager.IMPORTANCE_DEFAULT)); } }

    int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}    
    TextView t(String s,int z,boolean bold){ TextView v=new TextView(this);v.setText(s);v.setTextColor(TEXT);v.setTextSize(z);v.setPadding(0,dp(4),0,dp(4));if(bold)v.setTypeface(null,Typeface.BOLD);return v; }
    TextView note(String s){TextView v=t(s,14,false);v.setTextColor(MUTED);v.setPadding(0,0,0,dp(10));root.addView(v);return v;}
    Button btn(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(16);b.setOnClickListener(l);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(5),0,dp(5));root.addView(b,lp);return b;}
    void base(String title,String sub,boolean back){ ScrollView sv=new ScrollView(this);sv.setFillViewport(true);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(30));root.setBackgroundColor(BG); if(back){Button b=new Button(this);b.setText("← Tillbaka");b.setAllCaps(false);b.setOnClickListener(v->showHome());root.addView(b);} TextView h=t(title,28,true);h.setTextColor(ACC);root.addView(h);note(sub);sv.addView(root);setContentView(sv);}
    void card(String title,String body,View.OnClickListener l){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackgroundColor(Color.WHITE);TextView a=t(title,19,true);c.addView(a);TextView b=t(body,14,false);b.setTextColor(MUTED);c.addView(b);c.setOnClickListener(l);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(6),0,dp(6));root.addView(c,lp);}
    EditText input(String hint,int type){EditText e=new EditText(this);e.setHint(hint);e.setInputType(type);e.setPadding(dp(12),dp(10),dp(12),dp(10));return e;}
    String money(double x){return String.format(Locale.forLanguageTag("sv-SE"),"%,.0f kr",x);}
    JSONArray arr(String key){try{return new JSONArray(p.getString(key,"[]"));}catch(Exception e){return new JSONArray();}}
    void save(String key,JSONArray a){p.edit().putString(key,a.toString()).apply();}
    String today(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());}
    String month(){return new SimpleDateFormat("yyyy-MM",Locale.US).format(new Date());}
    long parseDate(String s){try{return new SimpleDateFormat("yyyy-MM-dd",Locale.US).parse(s).getTime();}catch(Exception e){return Long.MAX_VALUE;}}
    double dbl(String s){try{return Double.parseDouble(s.replace(",","."));}catch(Exception e){return 0;}}

    double balance(){double n=p.getFloat("start_balance",0);JSONArray a=arr("tx");for(int i=0;i<a.length();i++)try{JSONObject o=a.getJSONObject(i);double v=o.optDouble("amount");n+=("Inkomst".equals(o.optString("type"))?v:-v);}catch(Exception ignored){}return n;}
    double monthExpense(String ym){double n=0;JSONArray a=arr("tx");for(int i=0;i<a.length();i++)try{JSONObject o=a.getJSONObject(i);if("Utgift".equals(o.optString("type"))&&o.optString("date").startsWith(ym))n+=o.optDouble("amount");}catch(Exception ignored){}return n;}
    double plannedOpen(){double n=0;JSONArray a=arr("planned");for(int i=0;i<a.length();i++)try{JSONObject o=a.getJSONObject(i);if(!o.optBoolean("done"))n+=o.optDouble("amount");}catch(Exception ignored){}return n;}
    double billsOpen(){double n=0;JSONArray a=arr("bills");for(int i=0;i<a.length();i++)try{JSONObject o=a.getJSONObject(i);if(!o.optBoolean("paid"))n+=o.optDouble("amount");}catch(Exception ignored){}return n;}

    void showHome(){base("Min Ekonomi v2.1","Privat ekonomi • biometriskt lås • kalender • coach",false); card("💰 Totalt saldo",money(balance())+"\nPrognos efter planerat och obetalda räkningar: "+money(balance()-plannedOpen()-billsOpen()),v->showTransactions()); card("✨ Smarta insikter",insight(),v->showCoach()); card("🧾 Transaktioner","Inkomster och utgifter",v->showTransactions()); card("📅 Ekonomikalender","Räkningar och planerade köp i datumordning",v->showCalendar()); card("🛒 Planerade köp",money(plannedOpen())+" kvar planerat",v->showPlanned()); card("🧷 Räkningar",money(billsOpen())+" obetalt • påminnelser kan schemaläggas",v->showBills()); card("🎯 Sparmål",savingSummary(),v->showSavings()); card("📊 Budget & statistik","Månadsbudget, utgifter och utveckling",v->showBudget()); card("🧠 Ekonomicoach","Personliga råd utifrån dina lokala siffror",v->showCoach()); card("⚙️ Inställningar","Startsaldo, notiser och sekretess",v->showSettings());}

    String insight(){double cur=monthExpense(month());Calendar c=Calendar.getInstance();c.add(Calendar.MONTH,-1);String prev=new SimpleDateFormat("yyyy-MM",Locale.US).format(c.getTime());double old=monthExpense(prev);if(old<=0)return "Du har spenderat "+money(cur)+" den här månaden.";double d=old-cur;return d>=0?"Du har spenderat "+money(d)+" mindre än förra månaden.":"Du har spenderat "+money(-d)+" mer än förra månaden.";}

    void showTransactions(){base("Transaktioner","Lägg till, se och ta bort poster",true);btn("＋ Ny transaktion",v->transactionDialog());JSONArray a=arr("tx");if(a.length()==0){note("Inga transaktioner ännu.");return;}for(int i=a.length()-1;i>=0;i--){final int idx=i;try{JSONObject o=a.getJSONObject(i);String sign="Inkomst".equals(o.optString("type"))?"+":"−";card(o.optString("name","Post"),o.optString("date")+" • "+o.optString("category")+"\n"+sign+money(o.optDouble("amount")),v->confirmDelete("tx",idx,"Ta bort transaktionen?",this::showTransactions));}catch(Exception ignored){}}
    }
    void transactionDialog(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(16),0,dp(16),0);EditText name=input("Namn",1),amount=input("Belopp",2|8192),date=input("Datum (ÅÅÅÅ-MM-DD)",1);date.setText(today());Spinner type=new Spinner(this);type.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Utgift","Inkomst"}));Spinner cat=new Spinner(this);cat.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,CATS));l.addView(name);l.addView(amount);l.addView(date);l.addView(type);l.addView(cat);new AlertDialog.Builder(this).setTitle("Ny transaktion").setView(l).setNegativeButton("Avbryt",null).setPositiveButton("Spara",(d,w)->{try{JSONObject o=new JSONObject();o.put("id",System.currentTimeMillis());o.put("name",name.getText().toString());o.put("amount",dbl(amount.getText().toString()));o.put("date",date.getText().toString());o.put("type",type.getSelectedItem().toString());o.put("category",cat.getSelectedItem().toString());JSONArray a=arr("tx");a.put(o);save("tx",a);showTransactions();}catch(Exception ignored){}}).show();}

    void showPlanned(){base("Planerade köp","Markera som genomfört eller ta bort när du vill",true);btn("＋ Nytt planerat köp",v->plannedDialog());JSONArray a=arr("planned");if(a.length()==0){note("Inga planerade köp.");return;}for(int i=0;i<a.length();i++){final int idx=i;try{JSONObject o=a.getJSONObject(i);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(10),dp(12),dp(10));c.setBackgroundColor(Color.WHITE);TextView x=t((o.optBoolean("done")?"✓ ":"")+o.optString("name"),18,true);c.addView(x);TextView m=t(o.optString("date")+" • "+money(o.optDouble("amount")),14,false);m.setTextColor(MUTED);c.addView(m);if(!o.optBoolean("done")){Button done=new Button(this);done.setText("✓ Markera som genomfört");done.setAllCaps(false);done.setOnClickListener(v->completePlanned(idx));c.addView(done);}Button del=new Button(this);del.setText("Ta bort");del.setAllCaps(false);del.setOnClickListener(v->confirmDelete("planned",idx,"Ta bort planerat köp?",this::showPlanned));c.addView(del);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(6),0,dp(6));root.addView(c,lp);}catch(Exception ignored){}}
    }
    void plannedDialog(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText name=input("Vad vill du köpa?",1),amount=input("Belopp",2|8192),date=input("Planerat datum (ÅÅÅÅ-MM-DD)",1);date.setText(today());l.setPadding(dp(16),0,dp(16),0);l.addView(name);l.addView(amount);l.addView(date);new AlertDialog.Builder(this).setTitle("Nytt planerat köp").setView(l).setNegativeButton("Avbryt",null).setPositiveButton("Spara",(d,w)->{try{JSONObject o=new JSONObject();o.put("id",System.currentTimeMillis());o.put("name",name.getText().toString());o.put("amount",dbl(amount.getText().toString()));o.put("date",date.getText().toString());o.put("done",false);JSONArray a=arr("planned");a.put(o);save("planned",a);showPlanned();}catch(Exception ignored){}}).show();}
    void completePlanned(int idx){try{JSONArray a=arr("planned");JSONObject o=a.getJSONObject(idx);o.put("done",true);save("planned",a);JSONObject tx=new JSONObject();tx.put("id",System.currentTimeMillis());tx.put("name",o.optString("name"));tx.put("amount",o.optDouble("amount"));tx.put("date",today());tx.put("type","Utgift");tx.put("category","Shopping");JSONArray t=arr("tx");t.put(tx);save("tx",t);Toast.makeText(this,"Köpet är genomfört och bokfört som utgift.",Toast.LENGTH_LONG).show();showPlanned();}catch(Exception ignored){}}

    void showBills(){base("Räkningar","Obetalda räkningar och schemalagda påminnelser",true);btn("＋ Ny räkning",v->billDialog());JSONArray a=arr("bills");if(a.length()==0){note("Inga räkningar sparade.");return;}for(int i=0;i<a.length();i++){final int idx=i;try{JSONObject o=a.getJSONObject(i);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(10),dp(12),dp(10));c.setBackgroundColor(Color.WHITE);c.addView(t((o.optBoolean("paid")?"✓ ":"")+o.optString("name"),18,true));TextView m=t("Förfaller "+o.optString("date")+" • "+money(o.optDouble("amount")),14,false);m.setTextColor(MUTED);c.addView(m);if(!o.optBoolean("paid")){Button paid=new Button(this);paid.setText("Markera betald");paid.setAllCaps(false);paid.setOnClickListener(v->payBill(idx));c.addView(paid);Button rem=new Button(this);rem.setText("🔔 Schemalägg påminnelse");rem.setAllCaps(false);rem.setOnClickListener(v->scheduleBill(idx));c.addView(rem);}Button del=new Button(this);del.setText("Ta bort");del.setAllCaps(false);del.setOnClickListener(v->confirmDelete("bills",idx,"Ta bort räkningen?",this::showBills));c.addView(del);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(6),0,dp(6));root.addView(c,lp);}catch(Exception ignored){}}
    }
    void billDialog(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(16),0,dp(16),0);EditText name=input("Räkningens namn",1),amount=input("Belopp",2|8192),date=input("Förfallodatum (ÅÅÅÅ-MM-DD)",1);date.setText(today());l.addView(name);l.addView(amount);l.addView(date);new AlertDialog.Builder(this).setTitle("Ny räkning").setView(l).setNegativeButton("Avbryt",null).setPositiveButton("Spara",(d,w)->{try{JSONObject o=new JSONObject();o.put("id",System.currentTimeMillis());o.put("name",name.getText().toString());o.put("amount",dbl(amount.getText().toString()));o.put("date",date.getText().toString());o.put("paid",false);JSONArray a=arr("bills");a.put(o);save("bills",a);showBills();}catch(Exception ignored){}}).show();}
    void payBill(int idx){try{JSONArray a=arr("bills");JSONObject o=a.getJSONObject(idx);o.put("paid",true);save("bills",a);JSONObject tx=new JSONObject();tx.put("id",System.currentTimeMillis());tx.put("name",o.optString("name"));tx.put("amount",o.optDouble("amount"));tx.put("date",today());tx.put("type","Utgift");tx.put("category","Räkningar");JSONArray t=arr("tx");t.put(tx);save("tx",t);showBills();}catch(Exception ignored){}}
    void scheduleBill(int idx){try{JSONObject o=arr("bills").getJSONObject(idx);long due=parseDate(o.optString("date"));if(due==Long.MAX_VALUE){Toast.makeText(this,"Kontrollera datumformatet.",Toast.LENGTH_LONG).show();return;}Calendar c=Calendar.getInstance();c.setTimeInMillis(due);c.add(Calendar.DAY_OF_YEAR,-1);c.set(Calendar.HOUR_OF_DAY,9);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);Intent i=new Intent(this,ReminderReceiver.class);i.putExtra("name",o.optString("name"));i.putExtra("date",o.optString("date"));PendingIntent pi=PendingIntent.getBroadcast(this,(int)(o.optLong("id")&0x7fffffff),i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);AlarmManager am=(AlarmManager)getSystemService(ALARM_SERVICE);am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,c.getTimeInMillis(),pi);Toast.makeText(this,"Påminnelse schemalagd dagen före kl. 09:00.",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Kunde inte schemalägga påminnelsen.",Toast.LENGTH_LONG).show();}}

    void showCalendar(){base("Ekonomikalender","Kommande räkningar och planerade köp",true);ArrayList<JSONObject> list=new ArrayList<>();JSONArray b=arr("bills"),q=arr("planned");for(int i=0;i<b.length();i++)try{JSONObject x=new JSONObject(b.getJSONObject(i).toString());x.put("kind","Räkning");if(!x.optBoolean("paid"))list.add(x);}catch(Exception ignored){}for(int i=0;i<q.length();i++)try{JSONObject x=new JSONObject(q.getJSONObject(i).toString());x.put("kind","Planerat köp");if(!x.optBoolean("done"))list.add(x);}catch(Exception ignored){}Collections.sort(list,(a,z)->Long.compare(parseDate(a.optString("date")),parseDate(z.optString("date"))));if(list.isEmpty()){note("Kalendern är tom.");return;}for(JSONObject o:list)card(o.optString("date")+" • "+o.optString("kind"),o.optString("name")+"\n"+money(o.optDouble("amount")),null);}

    void showCoach(){base("Ekonomicoach","Råd baserat på informationen som bara finns på din enhet",true);double bal=balance(),pl=plannedOpen(),bill=billsOpen(),cur=monthExpense(month());Calendar c=Calendar.getInstance();c.add(Calendar.MONTH,-1);double prev=monthExpense(new SimpleDateFormat("yyyy-MM",Locale.US).format(c.getTime()));card("📌 Läget nu","Saldo "+money(bal)+" • Utgifter denna månad "+money(cur),null);if(prev>0){double d=cur-prev;card("📈 Jämförelse",d<=0?"Du ligger "+money(-d)+" lägre än förra månaden.":"Du ligger "+money(d)+" högre än förra månaden.",null);}double free=bal-bill-pl;card("🧮 Efter planerat",free>=0?"Efter räkningar och planerade köp återstår ungefär "+money(free)+".":"Planerade köp och räkningar överstiger nuvarande saldo med "+money(-free)+".",null);double budget=p.getFloat("monthly_budget",0);if(budget>0){double left=budget-cur;card("🎯 Budgetcoach",left>=0?"Du har "+money(left)+" kvar av månadsbudgeten.":"Månadsbudgeten är överskriden med "+money(-left)+".",null);}card("💡 Förslag","Prioritera räkningar först, kontrollera planerade köp innan de genomförs och använd sparmål för pengar du inte vill råka spendera.",null);}

    String savingSummary(){JSONArray a=arr("savings");double cur=0,target=0;for(int i=0;i<a.length();i++)try{JSONObject o=a.getJSONObject(i);cur+=o.optDouble("current");target+=o.optDouble("target");}catch(Exception ignored){}return a.length()==0?"Inga sparmål ännu.":money(cur)+" av "+money(target)+" sparat";}
    void showSavings(){base("Sparmål","Följ hur nära du är dina mål",true);btn("＋ Nytt sparmål",v->savingDialog());JSONArray a=arr("savings");if(a.length()==0){note("Inga sparmål ännu.");return;}for(int i=0;i<a.length();i++){final int idx=i;try{JSONObject o=a.getJSONObject(i);double cur=o.optDouble("current"),tar=o.optDouble("target");card(o.optString("name"),money(cur)+" av "+money(tar)+(tar>0?" • "+Math.min(100,(int)(cur/tar*100))+"%":""),v->savingAddDialog(idx));}catch(Exception ignored){}}}
    void savingDialog(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText n=input("Målets namn",1),t=input("Målbelopp",2|8192);l.addView(n);l.addView(t);new AlertDialog.Builder(this).setTitle("Nytt sparmål").setView(l).setNegativeButton("Avbryt",null).setPositiveButton("Spara",(d,w)->{try{JSONObject o=new JSONObject();o.put("name",n.getText().toString());o.put("target",dbl(t.getText().toString()));o.put("current",0);JSONArray a=arr("savings");a.put(o);save("savings",a);showSavings();}catch(Exception ignored){}}).show();}
    void savingAddDialog(int idx){EditText e=input("Belopp att lägga till",2|8192);new AlertDialog.Builder(this).setTitle("Lägg till sparande").setView(e).setNegativeButton("Avbryt",null).setPositiveButton("Lägg till",(d,w)->{try{JSONArray a=arr("savings");JSONObject o=a.getJSONObject(idx);o.put("current",o.optDouble("current")+dbl(e.getText().toString()));save("savings",a);showSavings();}catch(Exception ignored){}}).show();}

    void showBudget(){base("Budget & statistik","Månadsbudget och utgifter per kategori",true);double budget=p.getFloat("monthly_budget",0),spent=monthExpense(month());card("Månadsbudget",budget<=0?"Inte satt":money(spent)+" använt av "+money(budget),null);btn("Redigera månadsbudget",v->budgetDialog());HashMap<String,Double> m=new HashMap<>();JSONArray a=arr("tx");for(int i=0;i<a.length();i++)try{JSONObject o=a.getJSONObject(i);if("Utgift".equals(o.optString("type"))&&o.optString("date").startsWith(month())){String c=o.optString("category","Övrigt");m.put(c,m.getOrDefault(c,0.0)+o.optDouble("amount"));}}catch(Exception ignored){}if(m.isEmpty())note("Ingen utgiftsstatistik för den här månaden ännu.");else{ArrayList<Map.Entry<String,Double>> es=new ArrayList<>(m.entrySet());Collections.sort(es,(x,y)->Double.compare(y.getValue(),x.getValue()));for(Map.Entry<String,Double> e:es)card(e.getKey(),money(e.getValue()),null);}}
    void budgetDialog(){EditText e=input("Månadsbudget",2|8192);e.setText(String.valueOf(p.getFloat("monthly_budget",0)));new AlertDialog.Builder(this).setTitle("Månadsbudget").setView(e).setNegativeButton("Avbryt",null).setPositiveButton("Spara",(d,w)->{p.edit().putFloat("monthly_budget",(float)dbl(e.getText().toString())).apply();showBudget();}).show();}

    void showSettings(){base("Inställningar","Sekretess och grundvärden",true);card("🔒 Sekretess","Appens innehåll döljs i Androids appväxlare via FLAG_SECURE. Biometrisk verifiering används vid start när sensorn är tillgänglig.",null);btn("Ändra startsaldo",v->startBalanceDialog());btn("Skicka testnotis",v->testNotification());btn("Rensa all lokal data",v->new AlertDialog.Builder(this).setTitle("Rensa all data?").setMessage("Alla poster i Min Ekonomi tas bort.").setNegativeButton("Avbryt",null).setPositiveButton("Rensa",(d,w)->{p.edit().clear().apply();showHome();}).show());note("Version 2.1 • All ekonomidata sparas lokalt i appens privata lagring.");}
    void startBalanceDialog(){EditText e=input("Startsaldo",2|8192);e.setText(String.valueOf(p.getFloat("start_balance",0)));new AlertDialog.Builder(this).setTitle("Startsaldo").setView(e).setNegativeButton("Avbryt",null).setPositiveButton("Spara",(d,w)->{p.edit().putFloat("start_balance",(float)dbl(e.getText().toString())).apply();showSettings();}).show();}
    void testNotification(){Intent i=new Intent(this,ReminderReceiver.class);i.putExtra("name","Testnotis");i.putExtra("date",today());sendBroadcast(i);Toast.makeText(this,"Testnotis skickad.",Toast.LENGTH_SHORT).show();}

    void confirmDelete(String key,int idx,String msg,Runnable after){new AlertDialog.Builder(this).setTitle(msg).setNegativeButton("Avbryt",null).setPositiveButton("Ta bort",(d,w)->{JSONArray a=arr(key),n=new JSONArray();for(int i=0;i<a.length();i++)if(i!=idx)try{n.put(a.get(i));}catch(Exception ignored){}save(key,n);Toast.makeText(this,"Post borttagen",Toast.LENGTH_SHORT).show();after.run();}).show();}

    @Override public void onBackPressed(){showHome();}
}
